### ISSUE TITLE
What is the Username and Password for the Insurance Claim Self-Service Customer Login?

### ISSUE THREAD

**Issue by LennartFr** [IBM/build-blockchain-insurance-app#1]
Great app! Where do I find the Username and Password for the Insurance Claim Self-Service Customer Login?

**Comment by hossamsamy007** [comment]
@ lenaartfr i am facing some problems at building the project 
./build.sh 
#################################################################
#######        Generating cryptographic material       ##########
#################################################################
/root/build-blockchain-insurance-app/cryptogen: 1: /root/build-blockchain-insurance-app/cryptogen: ����: not found
/root/build-blockchain-insurance-app/cryptogen: 2: /root/build-blockchain-insurance-app/cryptogen: Syntax error: end of file unexpected (expecting ")")
===> Pulling fabric Images
==> FABRIC IMAGE: peer

x86_64-1.0.2: Pulling from hyperledger/fabric-peer
Digest: sha256:ce6e3c3d0f71641020184e4fe0615c2e65b5181664bad3d05942091917b73e28
Status: Image is up to date for hyperledger/fabric-peer:x86_64-1.0.2
==> FABRIC IMAGE: orderer

x86_64-1.0.2: Pulling from hyperledger/fabric-orderer
Digest: sha256:6427715d8c56b8778de30c7895287d0dd7bb9adb2f895337aac2dd3d0dcabca7
Status: Image is up to date for hyperledger/fabric-orderer:x86_64-1.0.2
==> FABRIC IMAGE: ccenv

x86_64-1.0.2: Pulling from hyperledger/fabric-ccenv
Digest: sha256:3ad83a302e633dea8fa3d9d95b3e68919b7754d81bd521d1c3744bd251d5a526
Status: Image is up to date for hyperledger/fabric-ccenv:x86_64-1.0.2
===> Pulling fabric ca Image
==> FABRIC CA IMAGE

x86_64-1.0.2: Pulling from hyperledger/fabric-ca
Digest: sha256:25ab46a951c17b3034b3555b339ba4a985148668959f96152a1e91bbd1c7dd57
Status: Image is up to date for hyperledger/fabric-ca:x86_64-1.0.2

===> List out hyperledger docker images
hyperledger/fabric-ca        x86_64-1.0.4        8e691b3509bf        6 weeks ago         238MB
hyperledger/fabric-couchdb   x86_64-1.0.4        cf24b91dfeb1        6 weeks ago         1.5GB
hyperledger/fabric-orderer   x86_64-1.0.4        b17741e7b036        6 weeks ago         151MB
hyperledger/fabric-peer      x86_64-1.0.4        1ce935adc397        6 weeks ago         154MB
hyperledger/fabric-ccenv     x86_64-1.0.4        856061b1fed7        6 weeks ago         1.28GB
hyperledger/fabric-ca        latest              7e53be14f804        3 months ago        238MB
hyperledger/fabric-ca        x86_64-1.0.2        7e53be14f804        3 months ago        238MB
hyperledger/fabric-orderer   latest              6efd17e86e65        3 months ago        151MB
hyperledger/fabric-orderer   x86_64-1.0.2        6efd17e86e65        3 months ago        151MB
hyperledger/fabric-peer      latest              0e2ed51971c9        3 months ago        154MB
hyperledger/fabric-peer      x86_64-1.0.2        0e2ed51971c9        3 months ago        154MB
hyperledger/fabric-ccenv     latest              d0f166e1a89e        3 months ago        1.28GB
hyperledger/fabric-ccenv     x86_64-1.0.2        d0f166e1a89e        3 months ago        1.28GB
hyperledger/fabric-orderer   x86_64-1.0.0        e317ca5638ba        5 months ago        179MB
hyperledger/fabric-peer      x86_64-1.0.0        6830dcd7b9b5        5 months ago        182MB
############################################################
#                 BUILDING CONTAINER IMAGES                #
############################################################
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM docker.io/hyperledger/fabric-orderer:x86_64-1.0.2
 ---> 6efd17e86e65
Step 2/3 : RUN mkdir /orderer
 ---> Using cache
 ---> 2f965624dee6
Step 3/3 : COPY crypto /orderer/crypto
COPY failed: stat /var/lib/docker/tmp/docker-builder353753187/crypto: no such file or directory
root@blockchain:~/build-blockchain-insurance-app#

**Comment by mahendra-panchal** [comment]
@LennartFr : did u get username and pwd.?

**Comment by rajiv180984** [comment]
I am getting exactly same error as mention by hossamsamy007. login successfully in dockerhub. Docker details are:
root@rajeev-VirtualBox:/home/rajeev# docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
Please help me to find the resolution of this problem.

**Comment by ljbennett62** [comment]
Insurance and pwd are denoted in the README: 
![image](https://user-images.githubusercontent.com/17774650/39066852-68663d9e-448b-11e8-9d9a-f9d5b7923ae4.png)
