### ISSUE TITLE
WEB work well, if LAN's IP on 192.168.xx.xx/24

### ISSUE THREAD

**Issue by chengc843988** [IBM/build-blockchain-insurance-app#11]
If you got *web* not work, I think the first step for debug is check your LAN interface not working on 172.xx.xx.xx/24 or 172.xx.xx.xx/16

change LAN'IP to 192.168.xx.xx/24 is working well!!

============================================================

1. I am using Ubuntu 16.04:
Linux chengc-OptiPlex-3050 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Docker version 17.12.0-ce, build c97c6d6
docker-compose version 1.18.0, build 8dd22a9
buildblockchaininsuranceapp_default netowkr IP: 172.17,18,9.XX.XX/16

try 2 test cases, booting from same hard disk, clear docker images,  download from git, and build_ubuntu.sh. 
1. in my Office LAN: 172.24.6.XX/24, web *DOES NOT WORK*.
2. at home LAN: 192.16.1.XX/24, web run well.

Had some tests on network,  'wget https://orderer0:7050 ' in any peernode (with command docker exec -it xxx-peer bash, wget ..), the peer nodes response me "https error", so the network is working well.

Because of using same computer, linux image, same test procedures, so I compare the difference between OFFICE and HOME env, and make sure the only difference is the network setting.
1. in office, I have let LAN off, or unplug the lan wire, not work.
2. in office, change docker0's IP/subnet to 10.XX.XX.XX/24 , not work
3. change LAN IP to 192.168.xx.xx/24, if *WORK*

So, I think, there is a bug with *DOCKER* network. 
I don't known how to change buildblockchaininsuranceapp_default's IP from 172.xx.xx.xx/16 to such as 192.168.XX.XX/24, or 10.XX.XX.XX/8, and I can't make sure how to fix this problem.

**Comment by ishangulhane** [comment]
@chengc843988 Try deploying the code on docker machine and then connect to web using <docker ip>:3000
