### ISSUE TITLE
Windows 7 :  err docker-compose up -d

### ISSUE THREAD

**Issue by sandeep20162017** [IBM/build-blockchain-insurance-app#14]
$ docker-compose up -d
Pulling shop-ca (shop-ca:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If
you continue, volume data could be lost. Consider backing up your data before c
ntinuing.

Continue with the new image? [yN]y
Pulling shop-ca (shop-ca:latest)...
ERROR: pull access denied for shop-ca, repository does not exist or may require
'docker login'

**Comment by ishangulhane** [comment]
@sandeep20162017 You need to login to your docker hub account before running the scripts
