### ISSUE TITLE
error: [Peer.js]: sendProposal - timed out after:45000

### ISSUE THREAD

**Issue by 694469927** [IBM/build-blockchain-insurance-app#18]
docker logs web

npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.3
npm info lifecycle blockchain-for-insurance@2.1.0~preserve: blockchain-for-insurance@2.1.0
npm info lifecycle blockchain-for-insurance@2.1.0~serve: blockchain-for-insurance@2.1.0

> blockchain-for-insurance@2.1.0 serve /app
> cross-env NODE_ENV=production node ./bin/server

/app/app/static/js
Server running on port: 3000
Default channel not found, attempting creation...
Successfully created a new default channel.
Joining peers to the default channel.
Chaincode is not installed, attempting installation...
Base container image present.
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
Successfully installed chaincode on the default channel.
error: [Peer.js]: sendProposal - timed out after:45000
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/app/node_modules/fabric-client/lib/Peer.js:124:19)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
Fatal error instantiating chaincode on some(all) peers!
Error: Proposal rejected by some (all) of the peers: Error: REQUEST_TIMEOUT
    at /app/www/blockchain/utils.js:248:15

**Comment by rico-bee** [comment]
I got the same issue

**Comment by ap050492** [comment]
Did anyone find any solution? I am also facing the same issue...

**Comment by subbaraok** [comment]
Check my comment for the issue #24 and see if it helps in resolving this as issue signature is similar

**Comment by ljbennett62** [comment]
@rico-bee - I have 1) updated the code and readme 3) pulled down to my local version and was successfully able to build and deploy the application. So I would suggest that you start fresh: 1) pull the latest code 2) clear out all your images using a docker stop and docker rmi commands 3) make sure you have the right version of node by installing nvm and pointing to the node version 8.11.3, docker 1.8 and npm 5.6.0. 3) Then dependent on your platform- run the right build command and everything should work.
