### ISSUE TITLE
while running ./build.sh COPY failed: stat /var/lib/docker/tmp/docker-builder640498754/crypto: no such file or directory

### ISSUE THREAD

**Issue by UPTYVG** [IBM/build-blockchain-insurance-app#2]
Linux dev-VirtualBox 4.10.0-42-generic #46~16.04.1-Ubuntu SMP
 x86_64 x86_64 x86_64 GNU/Linux

Step 3/3 : COPY crypto /orderer/crypto
COPY failed: stat /var/lib/docker/tmp/docker-builder640498754/crypto: no such file or directory

**Comment by mahendra-panchal** [comment]
I am facing same issue.
solved with fixing error found in log one by one.

define cryptogen configtxgen on valid path.

Each peer directory require crypto directory.

**Comment by rslu2000** [comment]
We have proposed our pull request for this problem.
Before the PR is permitted, you can git clone my fork link.
https://github.com/rslu2000/build-blockchain-insurance-app
and then just use the script ./build_mac.sh for mac user or ./build_ubuntu.sh for Ubuntu system.

**Comment by rajiv180984** [comment]
As per the error statement, Dockfile have statement "COPY /crypto /destinationLocation" but crypto folder is missing or crypto folder is missing or unable to find the respective directory. 
Solution : Manually create folder or copy  in same directory wher Dockfile [docker file]located. 
It solved my problem.

**Comment by rajiv180984** [comment]
Another issue ownership of user on directory where you clone the project. Script contail instruction[mkdir] to created crypto directory for peer, insurance, order etc. which failed due to insufficient priviledge. So change the ownership on folder build-blockchain-insurance-app using command chown -R user:usergroup.
It solved my problem.

**Comment by rajiv180984** [comment]
Please help me to resolve issue.
Step 4/5 : COPY tls /ca/tls
COPY failed: stat /var/lib/docker/tmp/docker-builder453403978/tls: no such file or directory

**Comment by rajiv180984** [comment]
I have run ./build successfully for this application . Docker-composed also run without any issue.
But web server seems failed to run. When I execute docker command **"docker logs web"**
I am getting follwoing error: 
root@rajeev-VirtualBox:/usr/local/IBM_Blockchain/build-blockchain-insurance-app# docker logs web
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.3
npm info lifecycle blockchain-for-insurance@2.1.0~preserve: blockchain-for-insurance@2.1.0
npm info lifecycle blockchain-for-insurance@2.1.0~serve: blockchain-for-insurance@2.1.0

> blockchain-for-insurance@2.1.0 serve /app
> cross-env NODE_ENV=production node ./bin/server

fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/app/certs/ordererOrg.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at fs.readFileSync (fs.js:510:33)
    at readCryptoFile (/app/bin/blockchain/config.js:13:57)
    at Object.<anonymous> (/app/bin/blockchain/config.js:23:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm info lifecycle blockchain-for-insurance@2.1.0~serve: Failed to exec serve script
npm ERR! Linux 4.4.0-109-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production node ./bin/server`
npm ERR! Exit status 1

Please help me to solve this issue.

**Comment by dineshnyr** [comment]
@rajiv180984 Could you please explain creation of crypto folder in more detail. I am not able to follow you.
