### ISSUE TITLE
error: [client-utils.js]: sendPeersProposal - Promise is rejected

### ISSUE THREAD

**Issue by khmurovich** [IBM/build-blockchain-insurance-app#20]
first time after a start, site working fine but after few minutes i get errors and site stop a work

sudo docker logs web
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.3
npm info lifecycle blockchain-for-insurance@2.1.0~preserve: blockchain-for-insurance@2.1.0
npm info lifecycle blockchain-for-insurance@2.1.0~serve: blockchain-for-insurance@2.1.0

> blockchain-for-insurance@2.1.0 serve /app
> cross-env NODE_ENV=production node ./bin/server

/app/app/static/js
Server running on port: 3000
Default channel not found, attempting creation...
Successfully created a new default channel.
Joining peers to the default channel.
Chaincode is not installed, attempting installation...
Base container image present.
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
Successfully installed chaincode on the default channel.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: API error (404): {"message":"network buildblockchaininsuranceapp_default not found"}

    at new createStatusError (/app/node_modules/grpc/src/client.js:64:15)
    at /app/node_modules/grpc/src/client.js:583:15
Fatal error instantiating chaincode on some(all) peers!
Error: Proposal rejected by some (all) of the peers: Error: 2 UNKNOWN: error starting container: API error (404): {"message":"network buildblockchaininsuranceapp_default not found"}

    at /app/www/blockchain/utils.js:248:15
    at next (native)
    at step (/app/bin/blockchain/utils.js:102:191)
    at /app/bin/blockchain/utils.js:102:361

npm info lifecycle blockchain-for-insurance@2.1.0~serve: Failed to exec serve script
npm ERR! Linux 4.8.0-49-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production node ./bin/server`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the blockchain-for-insurance@2.1.0 serve script 'cross-env NODE_ENV=production node ./bin/server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blockchain-for-insurance package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node ./bin/server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blockchain-for-insurance
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blockchain-for-insurance
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

**Comment by lakshadvani** [comment]
Did you resolve this?

**Comment by khmurovich** [comment]
@lakshadvani yes, but i get new error

sudo docker logs web
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.3
npm info lifecycle blockchain-for-insurance@2.1.0~preserve: blockchain-for-insurance@2.1.0
npm info lifecycle blockchain-for-insurance@2.1.0~serve: blockchain-for-insurance@2.1.0

> blockchain-for-insurance@2.1.0 serve /app
> cross-env NODE_ENV=production node ./bin/server

/app/app/static/js
Server running on port: 3000
Failed to configure event hubs. Error Cannot read property 'getConnectivityState' of undefined
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'getConnectivityState' of undefined
/app/node_modules/fabric-client/lib/EventHub.js:308
			if(self._stream) state = self._stream.call.channel_.getConnectivityState();
			                                                   ^

TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/app/node_modules/fabric-client/lib/EventHub.js:308:55)
    at emitOne (events.js:96:13)
    at ClientDuplexStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ClientDuplexStream.Readable.push (_stream_readable.js:134:10)
    at Object.onReceiveMessage (/app/node_modules/grpc/src/client_interceptors.js:1302:19)
    at InterceptingListener.recvMessageWithContext (/app/node_modules/grpc/src/client_interceptors.js:629:19)
    at /app/node_modules/grpc/src/client_interceptors.js:728:14

npm info lifecycle blockchain-for-insurance@2.1.0~serve: Failed to exec serve script
npm ERR! Linux 4.8.0-49-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production node ./bin/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blockchain-for-insurance@2.1.0 serve script 'cross-env NODE_ENV=production node ./bin/server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blockchain-for-insurance package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node ./bin/server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blockchain-for-insurance
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blockchain-for-insurance
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

**Comment by rhagarty** [comment]
@khmurovich - I'm seeing the same error you initially ran into. You stated you resolve it. Do you remember how?

**Comment by gerdwatmann** [comment]
@ishangulhane - having the same trouble as @rhagarty , @khmurovich and @lakshadvani . Seems like a common issue. Any ideas? Thanks! With kind regards Gerd.

```console
Gerds-MBP-2:build-blockchain-insurance-app user$ docker logs web
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.3
npm info lifecycle blockchain-for-insurance@2.1.0~preserve: blockchain-for-insurance@2.1.0
npm info lifecycle blockchain-for-insurance@2.1.0~serve: blockchain-for-insurance@2.1.0

> blockchain-for-insurance@2.1.0 serve /app
> cross-env NODE_ENV=production node ./bin/server

/app/app/static/js
Server running on port: 3000
Default channel not found, attempting creation...
Successfully created a new default channel.
Joining peers to the default channel.
Chaincode is not installed, attempting installation...
Base container image present.
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
Successfully installed chaincode on the default channel.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: API error (500): {"message":"Could not attach to network buildblockchaininsuranceapp_default: rpc error: code = NotFound desc = network buildblockchaininsuranceapp_default not found"}

    at new createStatusError (/app/node_modules/grpc/src/client.js:64:15)
    at /app/node_modules/grpc/src/client.js:583:15
Fatal error instantiating chaincode on some(all) peers!
Error: Proposal rejected by some (all) of the peers: Error: 2 UNKNOWN: error starting container: API error (500): {"message":"Could not attach to network buildblockchaininsuranceapp_default: rpc error: code = NotFound desc = network buildblockchaininsuranceapp_default not found"}

    at /app/www/blockchain/utils.js:248:15
    at next (native)
    at step (/app/bin/blockchain/utils.js:102:191)
    at /app/bin/blockchain/utils.js:102:361

npm info lifecycle blockchain-for-insurance@2.1.0~serve: Failed to exec serve script
npm ERR! Linux 4.9.87-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production node ./bin/server`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the blockchain-for-insurance@2.1.0 serve script 'cross-env NODE_ENV=production node ./bin/server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blockchain-for-insurance package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node ./bin/server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blockchain-for-insurance
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blockchain-for-insurance
npm ERR! There is likely additional logging output above.
```

**Comment by ap050492** [comment]
@Paullaw102 can you please explain step which we need to follow for resolving the error?
Thanks...

**Comment by khmurovich** [comment]
@rhagarty @ap050492 @lakshadvani I didn't resolve this issue. Another error was blocking this one...

@Paullaw102 and other who have resolved this issue, please tell how you did it.

**Comment by subbaraok** [comment]
@khmurovich Please see my comment in #24  and check to see if it helps.

**Comment by Paullaw102** [comment]
put all the files on the root bash instead of any sub-directory and do not use build_mac.sh instead of build_ubuntu.sh.

**Comment by Paullaw102** [comment]
BTW,If you guys get the wrong issues, pls run "apt update" and "apt upgrade" to renew all files system. Good luck everyone!

**Comment by khmurovich** [comment]
@Paullaw102 which files?

**Comment by khmurovich** [comment]
@ishangulhane @ljbennett62 @wwalisa @rslu2000 cold you help us please with this issue?

**Comment by ialexander26** [comment]
@Paullaw102 
I still don't understand how to follow your directions.  Can you please explain? 
Thanks.

**Comment by ljbennett62** [comment]
@ialexander26 @khmurovich - I have 1) updated the code and readme 3) pulled down to my local version and was successfully able to build and deploy the application. So I would suggest that you start fresh: 1) pull the latest code 2) clear out all your images using a docker stop and docker rmi commands 3) make sure you have the right version of node by installing nvm and pointing to the node version 8.11.3, docker 1.8 and npm 5.6.0. 3) Then dependent on your platform- run the right build command and everything should work.

**Comment by SirCipher** [comment]
Does anybody have a solution to this?

**Comment by Paullaw102** [comment]
Guys,
I shared my steps to successfully to run this repo:

my system is Ubuntu 16.04 server version.

In sudo model(#) input all commades

Step 1. input "apt update"
Step 2.input  "apt udgrade"
Step 3.input "apt install docker.io" ,installing  ubuntu 16.0.4 server default package.
Step 4.input "apt install docker-compose", same as above.
Step 5.input "apt install nodejs-legacy".
Step 6.input "apt install npm".
Step 7.input "apt install python".
Step 8.input "git clone https://github.com/IBM/build-blockchain-insurance-app.git".
Step 9.input "cd build-blockchain-insurance-app/".
Step 10.input "./build_ubuntu.sh".
Step 11.input "docker logs web".

After that,Enjoying this app-repo.

Any issues,pls contact me freely.

**Comment by ganzr** [comment]
I do what you said, but i just stuck in one of the steps. 
My system is Ubuntu 16.04
And node-----v8.11.3
npm-----v5.6.0
![image](https://user-images.githubusercontent.com/20966436/42446136-d3775464-83a7-11e8-9029-6a79e120bffe.png)

**Comment by ganzr** [comment]
@Paullaw102

**Comment by ganzr** [comment]
i do as the following steps and it works for me:

- input "docker network ps" to figure out the name of the network( it is "buildblockchaininsuranceapp_default" for me)

- go to ./peer-base.yaml and change **CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE**  to the corresponding network name.

- input"./clean.sh" to clean the docker containers and rebuild the app again

hope it works for u all too.
and thank you for your help @lll2657

**Comment by anaswarg** [comment]
@lll2657 your solution worked. now its up & running.
