### ISSUE TITLE
Unable to build insurance app

### ISSUE THREAD

**Issue by aggarwalakhil9** [IBM/build-blockchain-insurance-app#21]
I get the following error when i try to clean and build. Earlier it used to work fine, but something went wrong since yesterday, even though nothing was changed from the app perspective. 

```
Failed to configure event hubs. Error Cannot read property 'getConnectivityState' of undefined
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'getConnectivityState' of undefined
/app/node_modules/fabric-client/lib/EventHub.js:305
			if(self._stream) state = self._stream.call.channel_.getConnectivityState();
			                                                   ^

TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/app/node_modules/fabric-client/lib/EventHub.js:305:55)
    at emitOne (events.js:96:13)
    at ClientDuplexStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ClientDuplexStream.Readable.push (_stream_readable.js:134:10)
    at Object.onReceiveMessage (/app/node_modules/grpc/src/client_interceptors.js:1302:19)
    at InterceptingListener.recvMessageWithContext (/app/node_modules/grpc/src/client_interceptors.js:629:19)
    at /app/node_modules/grpc/src/client_interceptors.js:728:14
```

**Comment by lakshadvani** [comment]
Did you find a workaround to resolve this?

**Comment by khmurovich** [comment]
the same

**Comment by Hasil-Sharma** [comment]
Even I'm facing the same issue when I try deploying the application

**Comment by aggarwalakhil9** [comment]
@lakshadvani i am not able to resolve the exception completely but i tried commenting the EventHub code to just deploy the application. It started building now but i'm not sure what side effects will commenting the EventHub code bring in the application.

**Comment by lengyijun** [comment]
meet the same problem

**Comment by patrickodhiambo** [comment]
check the following fix, worked for me

https://github.com/IBM/build-blockchain-insurance-app/pull/23/files#diff-9abe8877ac54fccdd08abd16c19811daR28

**Comment by aggarwalakhil9** [comment]
@patrickodhiambo did you try it on mac os or linux?

**Comment by ljbennett62** [comment]
@aggarwalakhil9 @javaer2012 - I have 1) updated the code and readme 3) pulled down to my local version and was successfully able to build and deploy the application. So I would suggest that you start fresh: 1) pull the latest code 2) clear out all your images using a docker stop and docker rmi commands 3) make sure you have the right version of node by installing nvm and pointing to the node version 8.11.3, docker 1.8 and npm 5.6.0. 3) Then dependent on your platform- run the right build command and everything should work.
