### ISSUE TITLE
I am unable to run in windows 10

### ISSUE THREAD

**Issue by veda2wratha** [IBM/build-blockchain-insurance-app#22]
![capture](https://user-images.githubusercontent.com/13012984/39564104-779ae13a-4ed0-11e8-955f-68f31f4d2a97.PNG)
I am getting below error

Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM docker.io/hyperledger/fabric-orderer:x86_64-1.1.0
 ---> ce0c810df36a
Step 2/3 : RUN mkdir /orderer
 ---> Using cache
 ---> 77646794201a
Step 3/3 : COPY crypto /orderer/crypto
COPY failed: stat /var/lib/docker/tmp/docker-builder972142260/crypto: no such file or directory

**Comment by lengyijun** [comment]
docker login?

**Comment by veda2wratha** [comment]
Yes logged in docker
