### ISSUE TITLE
web CONTAINER cann't run

### ISSUE THREAD

**Issue by jeffyyang** [IBM/build-blockchain-insurance-app#24]
yanghongtaodeMacBook-Pro:build-blockchain-insurance-app JeffyYang$ docker run web
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.3
npm info lifecycle blockchain-for-insurance@2.1.0~preserve: blockchain-for-insurance@2.1.0
npm info lifecycle blockchain-for-insurance@2.1.0~serve: blockchain-for-insurance@2.1.0

> blockchain-for-insurance@2.1.0 serve /app
> cross-env NODE_ENV=production node ./bin/server

module.js:471
    throw err;
    ^

Error: Cannot find module './api.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:19:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm info lifecycle blockchain-for-insurance@2.1.0~serve: Failed to exec serve script
npm ERR! Linux 4.9.87-linuxkit-aufs

npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production node ./bin/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blockchain-for-insurance@2.1.0 serve script 'cross-env NODE_ENV=production node ./bin/server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blockchain-for-insurance package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node ./bin/server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blockchain-for-insurance
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blockchain-for-insurance
npm ERR! There is likely additional logging output above.

**Comment by yash-ibm** [comment]
I also getting the same error!!

**Comment by yash-ibm** [comment]
hey,
You can go to web/package.json
and do fabric-ca-client:"1.1.0"
and fabric-client:"1.1.1"

It worked for me.

**Comment by sivajik34** [comment]
I modified the file.
then sudo docker logs web
but still same errors
 then how to re-run again?

**Comment by the07** [comment]
@jeffyyang Did you find any luck ? I have the same issue, it was working until yesterday. Tried every possible solution.

**Comment by yash-ibm** [comment]
Use node version 8.11.3

**Comment by ljbennett62** [comment]
@yash-ibm - what do you mean "rebuild the web images" - do you mean - clear out the docker images and restart docker?

**Comment by yash-ibm** [comment]
After updating package.json , remove all the docker images and restart the docker

**Comment by sivajik34** [comment]
@yash-ibm now it is working fine.

**Comment by scottdangelo** [comment]
I still have this problem, even after the package.json update and rebuild of images.
Also, are you planning on implementing this fix on the master branch?

**Comment by subbaraok** [comment]
After cloning from the original IBM GIT, in the file build-blockchain-insurance-app/web/package.json

please append production with "&&" in lines 15 & 17. Post change below is what the lines should look like.

 "build:webpack": "cross-env NODE_ENV=production&& babel-node ./tools/build",
    "build:server": "babel www -d bin webpack.config.prod.js",
    "serve": "cross-env NODE_ENV=production&& node ./bin/server",
	
After make the change above retry and see if it helps. These changes are based on the fix at https://github.com/kentcdodds/cross-env/issues/13 

Worked for me and hence suggesting.

**Comment by yash-ibm** [comment]
@ljbennett62 FYI you should update FROM tag here  https://github.com/IBM/build-blockchain-insurance-app/blob/master/web/Dockerfile#L1 to node:8.11.1

**Comment by subbaraok** [comment]
@yash-ibm Even after updating Dockerfile#L1 to 8.11.1, Web container is unstable. Below is the snippet:

user1@user1System:~/try1/build-blockchain-insurance-app/web$ docker logs web

> blockchain-for-insurance@2.1.0 serve /app
> cross-env NODE_ENV=production node ./bin/server

/app/app/static/js
Server running on port: 3000
info: [EventHub.js]: _connect - options {"grpc.ssl_target_name_override":"insurance-peer","grpc.default_authority":"insurance-peer","grpc.max_receive_message_length":-1,"grpc.max_send_message_length":-1}
info: [EventHub.js]: _connect - options {"grpc.ssl_target_name_override":"shop-peer","grpc.default_authority":"shop-peer","grpc.max_receive_message_length":-1,"grpc.max_send_message_length":-1}
info: [EventHub.js]: _connect - options {"grpc.ssl_target_name_override":"repairshop-peer","grpc.default_authority":"repairshop-peer","grpc.max_receive_message_length":-1,"grpc.max_send_message_length":-1}
info: [EventHub.js]: _connect - options {"grpc.ssl_target_name_override":"police-peer","grpc.default_authority":"police-peer","grpc.max_receive_message_length":-1,"grpc.max_send_message_length":-1}
Default channel not found, attempting creation...
Successfully created a new default channel.
Joining peers to the default channel.
Chaincode is not installed, attempting installation...
Base container image present.
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
Successfully installed chaincode on the default channel.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: API error (404): {"message":"network buildblockchaininsuranceapp_default not found"}

    at new createStatusError (/app/node_modules/grpc/src/client.js:64:15)
    at /app/node_modules/grpc/src/client.js:583:15
Fatal error instantiating chaincode on some(all) peers!
Error: Proposal rejected by some (all) of the peers: Error: 2 UNKNOWN: error starting container: API error (404): {"message":"network buildblockchaininsuranceapp_default not found"}

    at /app/www/blockchain/utils.js:248:15
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/utils.js:102:191)
    at /app/bin/blockchain/utils.js:102:361
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production node ./bin/server`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the blockchain-for-insurance@2.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-01T07_15_06_302Z-debug.log

**Comment by subbaraok** [comment]
@khmurovich 
I have this working after updating the node to 8.11.1
The changes to file "/web/package.json" as I called out in #34  are not 100% consistent though

**Comment by ljbennett62** [comment]
@khmurovich - I have 1) updated the code and readme 3) pulled down to my local version and was successfully able to build and deploy the application. So I would suggest that you start fresh: 1) pull the latest code 2) clear out all your images using a docker stop and docker rmi commands 3) make sure you have the right version of node by installing nvm and pointing to the node version 8.11.3, docker 1.8 and npm 5.6.0. 3) Then dependent on your platform- run the right build command and everything should work.
