### ISSUE TITLE
Web Container builds but fails to run 

### ISSUE THREAD

**Issue by the07** [IBM/build-blockchain-insurance-app#26]
> blockchain-for-insurance@2.1.0 serve /app
> cross-env NODE_ENV=production node ./bin/server

module.js:471
    throw err;
    ^

Error: Cannot find module './api.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:19:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm info lifecycle blockchain-for-insurance@2.1.0~serve: Failed to exec serve script
npm ERR! Linux 4.13.0-39-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production node ./bin/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blockchain-for-insurance@2.1.0 serve script 'cross-env NODE_ENV=production node ./bin/server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blockchain-for-insurance package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node ./bin/server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blockchain-for-insurance
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blockchain-for-insurance
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

docker is logged in, tried with older grpc modules too and fabric-client v1.1.0 and fabric-ca-client v1.1.1. Any suggestions ?

**Comment by the07** [comment]
Also tried using older node versions. Node v6.10.0 and v 6.9.0

**Comment by yash-ibm** [comment]
Use fabric-client v1.1.1 and fabric-ca-client v1.1.0

**Comment by the07** [comment]
@yash-ibm tried it, no luck. Any other ideas ? Or could you help me understand why this issue occurs in the first place ?

**Comment by yash-ibm** [comment]
Yesterday, a new version of fabric-ca-client got release with version v1.1.1 and in web/package.json under dependencies both fabric-ca-client and fabric-client were latest in master branch, so when you were building the image for web, it install all those dependencies.

if you do exec into a running web container and go to file location /app/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js u will see it requires (./api.js) but it is not there so that's why it is failing, So I just downgraded those sdk to v1.1.0 and built web images again, and it worked fine for me.

**Comment by ljbennett62** [comment]
yes - I also just learned that 
![image](https://user-images.githubusercontent.com/17774650/39802454-f3d94a4c-5322-11e8-9e1c-df74182b093d.png)

**Comment by the07** [comment]
@yash-ibm I changed it and tried but still fails, and i am unable to exec into the web container as the web container fails to run. It builds successfully but fails to run.

**Comment by the07** [comment]
@yash-ibm What version of node are you using ? Dockerfile inside web has node version set to 6.11.3, tho i tried with lower versions too ( 6.10.0 and 6.9.0)

**Comment by the07** [comment]
@ljbennett62 Aren't the node_modules installed in the web container and shouldn't rebuilding the container reinstall all the modules ?

**Comment by the07** [comment]
Worked - Fixes - fabric-ca-client: 1.1.0, fabric-client: 1.1.1, grpc:1.9.1 in package.json inside the web container.

**Comment by ljbennett62** [comment]
@the07 - right - but you have to remove the node_modules dir so that the newer modules get added during the rebuilding

**Comment by the07** [comment]
@yash-ibm - No changes in the docker file, just added "grpc": "1.9.1", changed fabric-client and fabric-ca-client to the versions you mentioned. Everything works fine now. Thank you so much for helping out and explaining it to me. 

I do have another question though. I am running the app on Ubuntu inside VM. The web docker fails to run when the VM is running behind NAT (Promise rejected or user context fails), however everything works when its connected to the network thru a bridged adapter. Can you think of a possible reason why this is happening ?

**Comment by yash-ibm** [comment]
@the07 - Sorry for replying late, you cold refer to https://github.com/hyperledger/composer/issues/3974 for fixing your above Issue.  Your welcome!!!
