### ISSUE TITLE
App Is Unstable

### ISSUE THREAD

**Issue by KeshavReddy08** [IBM/build-blockchain-insurance-app#27]
After the build is completed .
My app is getting crashed on the first click and its throwing error Unable to connect

**Comment by subbaraok** [comment]
What's your host machine?

If using Ubuntu, check my comment in #24 and retry to see if it helps...

**Comment by ljbennett62** [comment]
@KeshavReddy08 -  I have 1) updated the code and readme 3) pulled down to my local version and was successfully able to build and deploy the application. So I would suggest that you  - start fresh : 1) pull the latest code 2) clear out all your images using a docker stop and docker rmi commands 3) make sure you have the right version of node by installing nvm and pointing to the node version 8.11.3, docker 1.8 and npm 5.6.0. 3) Then dependent on your platform- run the right build command and everything should work.
