### ISSUE TITLE
Docker image build taking too long

### ISSUE THREAD

**Issue by shrutisinha** [IBM/build-blockchain-insurance-app#28]
Can the docker build process be faster?
After every slight code change, the wait is too long for debugging.

**Comment by the07** [comment]
If I am not wrong, its the npm build which takes the longest. So I would suggest pre-installing them before running it as container. You will have to rebuild it if you make any changes to package.json. 

cd into web directory.
Run `npm i && npm i --only=dev`
In your web directory, open Dockerfile. Remove line 12 which is `&& npm i && npm i --only=dev \`.

Now when you run the build shell script, it shouldn't take long.

**Comment by ljbennett62** [comment]
@shrutisinha - yes - the build does take a bit longer than normal.
