### ISSUE TITLE
On running "sudo ./build_ubuntu.sh" command I am getting error

### ISSUE THREAD

**Issue by aakkss11** [IBM/build-blockchain-insurance-app#29]
On running "sudo ./build_ubuntu.sh" command I am getting error.

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Temporary failure resolving 'security.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'deb.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Temporary failure resolving 'deb.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Package build-essential is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'build-essential' has no installation candidate
The command '/bin/sh -c apt update && apt install -y build-essential       && npm i && npm i --only=dev       && npm run build       && npm prune       && apt remove -y build-essential' returned a non-zero code: 100
Creating network "build-blockchain-insurance-app_default" with the default driver
Pulling insurance-ca (insurance-ca:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling insurance-ca (insurance-ca:)...
ERROR: pull access denied for insurance-ca, repository does not exist or may require 'docker login'
anant@anant-VirtualBox:~/build-blockchain-insurance-app$ 

Please help me to resolve it.

**Comment by subbaraok** [comment]
docker login?

**Comment by Gurpret7** [comment]
I am also facing the same error even after docker login

**Comment by subbaraok** [comment]
@Gurpret7 What's the host OS you are using?

**Comment by Gurpret7** [comment]
Ubuntu 18 on VM

**Comment by subbaraok** [comment]
I have this working on Ubuntu 18 bare metal. Will check on a VM. I am assuming network is configured correctly since you could get the code.

**Comment by subbaraok** [comment]
@Gurpret7 OK just tested on Ubuntu 18.04 LTS VM. No issues. Let me know if you need anything in specific.

**Comment by Gurpret7** [comment]
@subbaraok Thanks for your response & time. 
while running the code, I m getting error
ERROR: pull access denied for insurance-ca, repository does not exist or may require 'docker login'
It worked for you fine. That sounds great!!
But why I m getting the error? if you can share any input. That would be appreciated.

**Comment by subbaraok** [comment]
@Gurpret7 please make sure to login to docker using "docker login" command. This step is immediately after cloning the repo.

**Comment by gnurtcouq** [comment]
You have error:
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease
...
Are you working behind corporate proxy. If this is the case, do the following:
Use this alias to create a docker-build command with proxy settings (chnage your_proxy:your_port with your corporate proxy seting):

Step 1:

cat << EOF >> ~/.bashrc
export HTTP_PROXY=http://your_proxy:your_port
export HTTPS_PROXY=http://your_proxy:your_port
EOF

Then source the new bashrc:

. ~/.bashrc

Step 2:

Edit file docker-images.sh and add proxy parameters in lines "docker build ..." as:

    docker build --build-arg http_proxy=http://your_proxy:your_port --build-arg https_proxy=http://your_proxy:your_port -t orderer:latest orderer/
    docker build --build-arg http_proxy=http://your_proxy:your_port --build-arg https_proxy=http://your_proxy:your_port -t insurance-peer:latest insurancePeer/
    docker build --build-arg http_proxy=http://your_proxy:your_port --build-arg https_proxy=http://your_proxy:your_port -t police-peer:latest policePeer/
    docker build --build-arg http_proxy=http://your_proxy:your_port --build-arg https_proxy=http://your_proxy:your_port -t shop-peer:latest shopPeer/
    docker build --build-arg http_proxy=http://your_proxy:your_port --build-arg https_proxy=http://your_proxy:your_port -t repairshop-peer:latest repairShopPeer/
    docker build --build-arg http_proxy=http://your_proxy:your_port --build-arg https_proxy=http://your_proxy:your_port -t web:latest web/
    docker build --build-arg http_proxy=http://your_proxy:your_port --build-arg https_proxy=http://your_proxy:your_port -t insurance-ca:latest insuranceCA/
    docker build --build-arg http_proxy=http://your_proxy:your_port --build-arg https_proxy=http://your_proxy:your_port -t police-ca:latest policeCA/
    docker build --build-arg http_proxy=http://your_proxy:your_port --build-arg https_proxy=http://your_proxy:your_port -t shop-ca:latest shopCA/
    docker build --build-arg http_proxy=http://your_proxy:your_port --build-arg https_proxy=http://your_proxy:your_port -t repairshop-ca:latest repairShopCA/

**Comment by dimasprase** [comment]
i have the similar error when running sudo ./build_ubuntu.sh
i'm running on Ubuntu 18.04
`Step 9/11 : RUN apt update && apt install -y build-essential       && npm i && npm i --only=dev       && npm run build       && npm prune       && apt remove -y build-essential
 ---> Running in a5da58b543ba

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

Err http://deb.debian.org jessie InRelease
  
Err http://security.debian.org jessie/updates InRelease
  
Err http://deb.debian.org jessie-updates InRelease
  
Err http://security.debian.org jessie/updates Release.gpg
  Temporary failure resolving 'security.debian.org'
Err http://deb.debian.org jessie Release.gpg
  Temporary failure resolving 'deb.debian.org'
Err http://deb.debian.org jessie-updates Release.gpg
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://security.debian.org/debian-security/dists/jessie/updates/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'deb.debian.org'

W: Failed to fetch http://security.debian.org/debian-security/dists/jessie/updates/Release.gpg  Temporary failure resolving 'security.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Temporary failure resolving 'deb.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Package build-essential is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'build-essential' has no installation candidate
The command '/bin/sh -c apt update && apt install -y build-essential       && npm i && npm i --only=dev       && npm run build       && npm prune       && apt remove -y build-essential' returned a non-zero code: 100
Pulling shop-ca (shop-ca:latest)...
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 952, in up
    start=not no_start
  File "/usr/lib/python2.7/dist-packages/compose/project.py", line 431, in up
    svc.ensure_image_exists(do_build=do_build)
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 312, in ensure_image_exists
    self.pull()
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 1029, in pull
    output = self.client.pull(repo, tag=tag, stream=True)
  File "/usr/lib/python2.7/dist-packages/docker/api/image.py", line 381, in pull
    header = auth.get_config_header(self, registry)
  File "/usr/lib/python2.7/dist-packages/docker/auth.py", line 50, in get_config_header
    authcfg = resolve_authconfig(client._auth_configs, registry)
  File "/usr/lib/python2.7/dist-packages/docker/auth.py", line 97, in resolve_authconfig
    authconfig, registry, store_name
  File "/usr/lib/python2.7/dist-packages/docker/auth.py", line 142, in _resolve_authconfig_credstore
    'Credentials store error: {0}'.format(repr(e))
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-secretservice exited with "Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached".',)`

**Comment by iiMajRaii** [comment]
I solved problem with step 9/11 by following this:
https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/

**Comment by hovig** [comment]
follow steps from [issue 58](https://github.com/IBM/build-blockchain-insurance-app/issues/58)
