### ISSUE TITLE
ERROR: pull access denied for shop-ca

### ISSUE THREAD

**Issue by UPTYVG** [IBM/build-blockchain-insurance-app#3]
dev@dev-VirtualBox:~/Downloads/build-blockchain-insurance-app$ docker-compose pull
Pulling shop-ca (shop-ca:latest)...
ERROR: pull access denied for shop-ca, repository does not exist or may require 'docker login'

**Comment by sathyamurthyp** [comment]
Same issue, any workaround?

**Comment by UPTYVG** [comment]
I did not try, but I suppose if you are using Windows OS you need to use other binaries for that. All existed now are for Mac OS.
it is necessary to run get-fabric-images.sh in the root of the repo.

**Comment by sathyamurthyp** [comment]
I am running in on a linux VM, I dont see a file named **get-fabric-images.sh** in the repo. Let me know if I am missing anything.

**Comment by UPTYVG** [comment]
I mean that it is necessary to this.
install the Hyperledger Fabric platform-specific binaries. 
curl -sSL https://goo.gl/byy2Qj | bash -s 1.0.5

**Comment by rslu2000** [comment]
We have proposed our pull request for this problem.
Before the PR is permitted, you can git clone my fork link.
https://github.com/rslu2000/build-blockchain-insurance-app
and then just use the script ./build_mac.sh for mac user or ./build_ubuntu.sh for Ubuntu system.

**Comment by Gurpret7** [comment]
@rslu2000  still facing same error
Pulling insurance-ca (insurance-ca:)...
ERROR: pull access denied for insurance-ca, repository does not exist or may require 'docker login'

**Comment by gnurtcouq** [comment]
Hi All,
I have the same error in Ubuntu 16_04 on VirtualBox:

ERROR: pull access denied for shop-ca, repository does not exist or may require 'docker login'

Issue command docker login & can login successfully. But the same error still happens when I tried to run:

./build_ubuntu.sh

Any help?

**Comment by sblisztomaniac** [comment]
ERROR: pull access denied for shop-ca, repository does not exist or may require 'docker login'
same error,any workaround?
