### ISSUE TITLE
Error in JS file

### ISSUE THREAD

**Issue by onenesskura** [IBM/build-blockchain-insurance-app#33]
![screenshot from 2018-06-07 18-18-26](https://user-images.githubusercontent.com/39981054/41100714-b5f1359a-6a7f-11e8-914a-5d2baa33c6d5.png)
Could anyone let me know how to solve the errors in this image while building in Ubuntu

**Comment by ljbennett62** [comment]
@onenesskura - I have 1) updated the code and readme 3) pulled down to my local version and was successfully able to build and deploy the application. So I would suggest that you start fresh: 1) pull the latest code 2) clear out all your images using a docker stop and docker rmi commands 3) make sure you have the right version of node by installing nvm and pointing to the node version 8.11.3, docker 1.8 and npm 5.6.0. 3) Then dependent on your platform- run the right build command and everything should work.
