### ISSUE TITLE
Error while building the project:  Promise is rejected: Error: 2 UNKNOWN: error starting container: 

### ISSUE THREAD

**Issue by Akhi03** [IBM/build-blockchain-insurance-app#34]
Dear Developers,

Could anyone help me solve the below problem.

![screenshot from 2018-06-08 13-37-58](https://user-images.githubusercontent.com/39798127/41149971-85dd4d84-6b2a-11e8-8dab-cf6634d36ddb.png)

[client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: API error (404): {"message":"network buildblockchaininsuranceapp_default not found"}

I have updated all my node modules and installed all the per-requisites.

Thank you

**Comment by ljbennett62** [comment]
so i have node version 10.4.0 - I actually thought you need to be on version 8+. If you upgrade - i would start fresh - remove the directory and clone it fresh; clean up docker (remove images) and then run it again

**Comment by GuilleCoduri** [comment]
Hi! I am on version 8.9 and i got the same error.

**Comment by rajqumar** [comment]
Please assign to someone

**Comment by khmurovich** [comment]
@Akhi03 @GuilleCoduri did you resolve this issue?

**Comment by fariza-z** [comment]
I am having the same problem, did any of you manage to solve this issue? @Akhi03 @GuilleCoduri @ialexander28

**Comment by khmurovich** [comment]
the same issue

**Comment by ialexander28** [comment]
![image](https://user-images.githubusercontent.com/29103853/41672490-48997974-7477-11e8-8cde-0cf81a72bf55.png)

**Comment by ialexander28** [comment]
Still not working

**Comment by rachit-khare** [comment]
I was able to get the app to run by changing the network name in peer-base.yaml file. For some reason the network that is generated with the scripts is hyphenated. Had to run ./clean.sh after making the change and re-running ./build_mac.sh (haven't tested this on ubuntu). Works after that.

`- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=build-blockchain-insurance-app_default`

![image](https://user-images.githubusercontent.com/28241306/41941111-ddb04b8c-794f-11e8-9bf0-15abe88b1bb3.png)

**Comment by ljbennett62** [comment]
@Akhi03, @ialexander28, fariza-z - putting all the advice here - I have 1) updated the code and readme 3) pulled down to my local version and was successfully able to build and deploy the application.  So I would suggest that you start fresh: 1) pull the latest code 2) clear out all your images using a docker stop and docker rmi commands 3) make sure you have the right version of node by installing nvm and pointing to the node version 8.11.3, docker 1.8 and npm 5.6.0.  3) Then dependent on your platform- run the right build command and everything should work.

**Comment by waburahmeh** [comment]
I Have the same issue,any help please.

**Comment by dcabib** [comment]
Same error...


> blockchain-for-insurance@2.1.0 serve /app
> cross-env NODE_ENV=production&&node ./bin/server

/app/app/static/js
Server running on port: 3000
Default channel not found, attempting creation...
Successfully created a new default channel.
Joining peers to the default channel.
Chaincode is not installed, attempting installation...
Base container image present.
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
Successfully installed chaincode on the default channel.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: API error (404): {"message":"network build-blockchain-insurance-app_default not found"}

    at new createStatusError (/app/node_modules/grpc/src/client.js:64:15)
    at /app/node_modules/grpc/src/client.js:583:15
Fatal error instantiating chaincode on some(all) peers!
Error: Proposal rejected by some (all) of the peers: Error: 2 UNKNOWN: error starting container: API error (404): {"message":"network build-blockchain-insurance-app_default not found"}

    at /app/www/blockchain/utils.js:248:15
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/utils.js:102:191)
    at /app/bin/blockchain/utils.js:102:361
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production&&node ./bin/server`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the blockchain-for-insurance@2.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-20T18_41_18_213Z-debug.log

**Comment by Akakandelwa** [comment]
I suspect this issue is related to issue #45.

See this: #45 (comment)

**Comment by ljbennett62** [comment]
pattern is getting updated - so this went away
