### ISSUE TITLE
Getting Below error during build the project

### ISSUE THREAD

**Issue by ankitshukla2018** [IBM/build-blockchain-insurance-app#35]
Hi Friends

I am getting below error while running the ./build_ubantu.sh script , script ran and it tooks almost 15 minutes then suddenly got multiple red events and at last getting below error message.
Any help will be really helpful.
thanks
![screenshot from 2018-06-12 13-34-16](https://user-images.githubusercontent.com/40197196/41277721-a11abf1e-6e45-11e8-9c37-7f7636265c4c.png)

**Comment by ljbennett62** [comment]
@Akhi03, @ialexander28, fariza-z - putting all the advice here - I have 1) updated the code and readme 3) pulled down to my local version and was successfully able to build and deploy the application. So I would suggest that you start fresh: 1) pull the latest code 2) clear out all your images using a docker stop and docker rmi commands 3) make sure you have the right version of node by installing nvm and pointing to the node version 8.11.3, docker 1.8 and npm 5.6.0. 3) Then dependent on your platform- run the right build command and everything should work.

**Comment by hovig** [comment]
check [issue 58](https://github.com/IBM/build-blockchain-insurance-app/issues/58)
