### ISSUE TITLE
执行 ./build_ubuntu.sh 出现如下错误

### ISSUE THREAD

**Issue by QQyushuqiu** [IBM/build-blockchain-insurance-app#37]
![image](https://user-images.githubusercontent.com/37897059/42208371-9f4d0e0e-7ede-11e8-9374-f301b9b2cb95.png)

**Comment by daocha** [comment]
It clearly says you need to login docker hub by calling : docker login

**Comment by dineshnyr** [comment]
I am getting the same error. Docker login is successful but even though this error comes. Any idea how to tackle this?

**Comment by rameelrahman** [comment]
@dineshnyr - Did you login to docker from cli? The username you should give while login is the on you see on the top right corner of the browesr after login to Docker Hub from browser, not your email id which you use to login to docker on a browser.

**Comment by ljbennett62** [comment]
pattern is getting updated so issue went away
