### ISSUE TITLE
Error: 2 UNKNOWN: error starting container: context deadline exceeded

### ISSUE THREAD

**Issue by in234** [IBM/build-blockchain-insurance-app#39]
Can anyone help me out with this? I looked at the other issues and tried the solutions but those didnt seem to work. I managed to run the build_ubuntu.sh script and it all worked fine. I'm running this on ubuntu 16.04.

I changed my build_ubuntu script to this:

`#!/bin/bash

cp ./binary_ubuntu/* .
export FABRIC_CFG_PATH=$PWD
sh ./ibm_fabric.sh
sh ./docker-images.sh
sleep 5
docker-compose up --no-start --force-recreate
sleep 60
docker-compose up -d --force-recreate`

After checking the logs of the web container, i get:

![screenshot from 2018-07-10 14-50-39](https://user-images.githubusercontent.com/7961629/42501140-ac8b046e-8450-11e8-91e7-359970860446.png)

**Comment by hovig** [comment]
@in234 

* run `./clean.sh` to get rid of existing images and containers and then run it with `./build_*.sh`.
* The project is updated with the latest fabric now
