### ISSUE TITLE
error while ./build.sh

### ISSUE THREAD

**Issue by hossamsamy007** [IBM/build-blockchain-insurance-app#4]
Step 3/3 : COPY crypto /orderer/crypto
COPY failed: stat /var/lib/docker/tmp/docker-builder217695668/crypto: no such file or directory

**Comment by tommy981407** [comment]
Same problem, any workaround?

**Comment by rjayaswal** [comment]
Workaround is that execute all commands that are part of build.sh file manually one by one.

**Comment by mahendra-panchal** [comment]
I am facing same issue.
solved with fixing error found in log one by one.
Check logs
You can see error like : 

/home/mahendra/project/hyperledger-test-project/build-blockchain-insurance-app/cryptogen: 1: /home/mahendra/project/hyperledger-test-project/build-blockchain-insurance-app/cryptogen: ����: not found

**define cryptogen configtxgen on valid path.**

mkdir: cannot create directory ‘/home/mahendra/project/hyperledger-test-project/build-blockchain-insurance-app/{orderer,insurancePeer,policePeer,repairShopPeer,shopPeer}/crypto’: No such file or directory
===> Pulling fabric Images
==> FABRIC IMAGE: peer

create crypto directory in {orderer,insurancePeer,policePeer,repairShopPeer,shopPeer} each directory.

This fixed my problem.

**Comment by rslu2000** [comment]
We have proposed our pull request for this problem.
Before the PR is permitted, you can git clone my fork link.
https://github.com/rslu2000/build-blockchain-insurance-app
and then just use the script  ./build_mac.sh for mac user or ./build_ubuntu.sh for Ubuntu system.

**Comment by rajiv180984** [comment]
I am also stuck with this problem. But Surprisingly I did not found any difference from rslu2000's code. 
and  ./build_mac.sh for mac user or ./build_ubuntu.sh are missing.

**Comment by rslu2000** [comment]
find the code here- https://github.com/rslu2000/build-blockchain-insurance-app

**Comment by rajiv180984** [comment]
Please help me to run this application. For me all docker image build successfully for this application.
[./build.sh completed successfully without any issue.]
Docker compose also worked fine without any issue or warning.
But I am gettinng error to start web -server. 
I run command "docker logs web" and  getting following error. 
root@rajeev-VirtualBox:/usr/local/IBM_Blockchain/build-blockchain-insurance-app# docker logs web
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.3
npm info lifecycle blockchain-for-insurance@2.1.0~preserve: blockchain-for-insurance@2.1.0
npm info lifecycle blockchain-for-insurance@2.1.0~serve: blockchain-for-insurance@2.1.0

> blockchain-for-insurance@2.1.0 serve /app
> cross-env NODE_ENV=production node ./bin/server

fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/app/certs/ordererOrg.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at fs.readFileSync (fs.js:510:33)
    at readCryptoFile (/app/bin/blockchain/config.js:13:57)
    at Object.<anonymous> (/app/bin/blockchain/config.js:23:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm info lifecycle blockchain-for-insurance@2.1.0~serve: Failed to exec serve script
npm ERR! Linux 4.4.0-109-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production node ./bin/server`
npm ERR! Exit status 1

Big Thanks to look into issue and suggestion.

**Comment by chengc843988** [comment]
See https://github.com/chengc843988/build-blockchain-insurance-app/blob/master/build_ubuntu.sh
because of ./web module's javascrip not all loaded!!
in build script, add 
npm install
but also make sure you have nodejs 6.X.X, hyperledger seems work with nodejs 6.x.x

**Comment by ishangulhane** [comment]
@rajiv180984 The certificates for the network are not generated. Try to set up the network again. If you're still facing the issues, then run the commands from script files manually.

**Comment by chengc843988** [comment]
For me, change the host system's lan/wifi ip addresses to 192.168.xx.xx, it's OK.
