### ISSUE TITLE
it's not connected offen after build_ubuntu.sh command complete

### ISSUE THREAD

**Issue by WoodyBae** [IBM/build-blockchain-insurance-app#42]
message on the console 
=================================================
Successfully built 50d4fceb0c09
Successfully tagged repairshop-ca:latest
Recreating shop-ca
Recreating orderer0
Recreating repairshop-ca
Recreating police-ca
Recreating insurance-ca
**WARNING: Connection pool is full, discarding connection: localhost**
Recreating insurance-peer
Recreating shop-peer
Recreating repairshop-peer
Recreating web
Recreating police-peer

**Comment by ljbennett62** [comment]
pattern is updated - so issue went away
