### ISSUE TITLE
Where is the data stored?

### ISSUE THREAD

**Issue by anushaath** [IBM/build-blockchain-insurance-app#43]
I see from the  [build-blockchain-insurance-app/docker-compose.yaml](https://github.com/IBM/build-blockchain-insurance-app/blob/master/docker-compose.yaml) file that there are no couch-db containers defined. So if there are no database related to each peer, then how/where is all the data from the application being stored?

If we're restarting the application, the previous transactions are lost, how do we stop that from happening?

**Comment by ljbennett62** [comment]
@anushaath - I believe it is using levelDB for storage.  You can view the following pattern to see the difference between using levelDB and couchDB: https://github.com/IBM/FabricNodeSDK-Starter

**Comment by anushaath** [comment]
Oh yes. The application uses LevelDB for storage. 
But the application does not have persistent storage.
