### ISSUE TITLE
Promise is rejected: Error: 2 UNKNOWN: error starting container: API error (404): {"message":"network build-blockchain-insurance-app_default not found"}

### ISSUE THREAD

**Issue by dcabib** [IBM/build-blockchain-insurance-app#45]
I've just download git repository and during build_ubuntu.sh, I've got the follow error message:

- - - - - -  - - -

user@ubuntu:~/Insurance/build-blockchain-insurance-app$ docker logs web

> blockchain-for-insurance@2.1.0 serve /app
> cross-env NODE_ENV=production&&node ./bin/server

/app/app/static/js
Server running on port: 3000
Default channel not found, attempting creation...
Successfully created a new default channel.
Joining peers to the default channel.
Chaincode is not installed, attempting installation...
Base container image present.
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
Successfully installed chaincode on the default channel.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: API error (404): {"message":"network build-blockchain-insurance-app_default not found"}

    at new createStatusError (/app/node_modules/grpc/src/client.js:64:15)
    at /app/node_modules/grpc/src/client.js:583:15
Fatal error instantiating chaincode on some(all) peers!
Error: Proposal rejected by some (all) of the peers: Error: 2 UNKNOWN: error starting container: API error (404): {"message":"network build-blockchain-insurance-app_default not found"}

    at /app/www/blockchain/utils.js:248:15
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/utils.js:102:191)
    at /app/bin/blockchain/utils.js:102:361
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production&&node ./bin/server`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the blockchain-for-insurance@2.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-20T18_41_18_213Z-debug.log

**Comment by parsiya** [comment]
1. Run `./clean.sh` to clean everything up.
2. Edit `build-blockchain-insurance-app/peer-base.yaml` file. Search for the following:
    `CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=build-blockchain-insurance-app_default`
3. Replace the line with:
    `CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=buildblockchaininsuranceapp_default`
4. Run `./build_ubuntu`.

The docker network name in the `peer-base.yaml` file is different from docker network name when setup in Ubuntu. Editing the file and renaming it will fix the problem.

**Comment by dcabib** [comment]
Thanks a lot @parsiya .... It is working now.....

**Comment by Akakandelwa** [comment]
Much appreciated, @parsiya!

That sorted that fixed the issue for me and the chaincode was able to initiate.

**Comment by sblisztomaniac** [comment]
ERROR: pull access denied for shop-ca, repository does not exist or may require 'docker login'

I followed the mentioned steps @parsiya  but i am getting the above mentioned error, any help would be appreciated,Thank you.

**Comment by sblisztomaniac** [comment]
Having the same issue,  even if I run a prior commit.

**Comment by ljbennett62** [comment]
pattern is updated so issue went away
