### ISSUE TITLE
pull access denied for shop-ca,  repository does not exist or may require 'docker login

### ISSUE THREAD

**Issue by dineshnyr** [IBM/build-blockchain-insurance-app#46]
All instructions have been followed properly. Docker login is also successful. I am getting this error after running ./build_ubuntu.sh.

`Step 3/3 : COPY crypto /orderer/crypto
COPY failed: stat /var/lib/docker/tmp/docker-builder195769509/crypto: no such file or directory
Pulling shop-ca (shop-ca:latest)...
**ERROR: pull access denied for shop-ca, repository does not exist or may require 'docker login'**`

**Comment by kashyapan** [comment]
Follow this link and make sure that you can run `docker` commands without sudo [link](https://docs.docker.com/install/linux/linux-postinstall/)

Similarly you must be able to install packages via npm without sudo ( globally )
if you can't then follow instructions here [link](https://stackoverflow.com/questions/49744276/error-cannot-find-module-api-hyperledger-composer)

After you are done execute `./clean.sh` and `./build_ubuntu.sh`  ( both without sudo )

Hope it helps!

**Comment by hovig** [comment]
@dineshnyr - check [issue 58](https://github.com/IBM/build-blockchain-insurance-app/issues/58).
