### ISSUE TITLE
Server stops abruptly

### ISSUE THREAD

**Issue by rameelrahman** [IBM/build-blockchain-insurance-app#47]
I have strictly followed the instructions said in the readme and the web site load successfully and menu were also accessible. But after few seconds the site goes down abruptly without any warning. I checked the error log using "docker log web" and found that the entire application is going down. I'm not able to find out the exact reason for that. Could you please suggest any solution or ways to find the reason for the issue. Thanks in advance.

Regards,
Rameel

**Comment by rameelrahman** [comment]
Please find below the docker log:

Base container image present.
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
Successfully installed chaincode on the default channel.
(node:22) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at /app/www/routers/shop.router.js:49:19
    at Generator.next (<anonymous>)
    at step (/app/bin/routers/shop.router.js:20:191)
    at /app/bin/routers/shop.router.js:20:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rameelrahman** [comment]
Hi Parsiya, Thanks for the quick response.
I'm able to access the menu  and some pages in the flow, but within 30 secs the entire application stops and nothing is accessible after that. I need to restart the application again and the same repeats.

**Comment by parsiya** [comment]
The web server starts first and then starts to install chaincode on the channel and perform other actions. If there's an error, it will shut down.

The web server contacts the shop peer and gets the contract types, then writes them to the channel in the second block. Looking at the error log, it seems like it cannot read the contract types from the shop peer. See here: https://github.com/IBM/build-blockchain-insurance-app/blob/master/web/www/routers/shop.router.js#L49.

After you get the error, use `docker ps` to see if the shop peer is running.

Were you running docker containers or examples before? They might be already running. Do `docker-compose stop` inside the directory of insurance app and then run `docker ps` to see if there are any other containers running. The insurance app assumes there are no other containers and then tries to contact specific ports.

You can also retry using a clean start, `docker images -a` will delete all previous images and `./clean.sh` will start downloading everything again. If you are using a slow connection, it will take a while to redownload the images. So use it as a last option.

**Comment by rameelrahman** [comment]
Thanks Parsiya,
I will check the options you said and get back...

**Comment by rameelrahman** [comment]
I did docker-compose stop
then
./clean.sh
then re-run the app, but still the same error coming up. Checked and found that all the peers are run. Please find below the error log.

Successfully installed chaincode on the default channel.
(node:24) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at /app/www/routers/shop.router.js:49:19
    at Generator.next (<anonymous>)
    at step (/app/bin/routers/shop.router.js:20:191)
    at /app/bin/routers/shop.router.js:20:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error: [Peer.js]: sendProposal - timed out after:45000
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: REQUEST_TIMEOUT
    at Timeout._onTimeout (/app/node_modules/fabric-client/lib/Peer.js:124:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
Fatal error instantiating chaincode on some(all) peers!
Error: Proposal rejected by some (all) of the peers: Error: REQUEST_TIMEOUT
    at /app/www/blockchain/utils.js:248:15
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/utils.js:102:191)
    at /app/bin/blockchain/utils.js:102:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production&&node ./bin/server`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the blockchain-for-insurance@2.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-30T15_26_00_771Z-debug.log

**Comment by rameelrahman** [comment]
Result of Docker ps:

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                              NAMES
3340aa0f0562        police-peer         "peer node start"        7 minutes ago       Up 7 minutes        0.0.0.0:10051->7051/tcp, 0.0.0.0:10053->7053/tcp   police-peer
9c4deb73b744        repairshop-peer     "peer node start"        7 minutes ago       Up 7 minutes        0.0.0.0:9051->7051/tcp, 0.0.0.0:9053->7053/tcp     repairshop-peer
dda6603d81ee        shop-peer           "peer node start"        7 minutes ago       Up 7 minutes        0.0.0.0:8051->7051/tcp, 0.0.0.0:8053->7053/tcp     shop-peer
209e1a72bd34        insurance-peer      "peer node start"        7 minutes ago       Up 7 minutes        0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp     insurance-peer
d6effa7f2dca        police-ca           "fabric-ca-server st…"   7 minutes ago       Up 7 minutes        0.0.0.0:10054->7054/tcp                            police-ca
5f9a6c539aa2        shop-ca             "fabric-ca-server st…"   7 minutes ago       Up 7 minutes        0.0.0.0:8054->7054/tcp                             shop-ca
7e7966e0166a        orderer             "orderer"                7 minutes ago       Up 7 minutes        0.0.0.0:7050->7050/tcp                             orderer0
32247e4e696b        insurance-ca        "fabric-ca-server st…"   7 minutes ago       Up 7 minutes        0.0.0.0:7054->7054/tcp                             insurance-ca
6770d6f93989        repairshop-ca       "fabric-ca-server st…"   7 minutes ago       Up 7 minutes        0.0.0.0:9054->7054/tcp                             repairshop-ca

**Comment by parsiya** [comment]
Thanks for providing the info.

The errors just tell us, it could not instantiate the chaincode, the instantiation for the chaincode is storing all insurance contracts on the ledger. It grabs them from the shop peer. It seems like it cannot get it from the shop peer.

Try looking at the logs for the shop peer, it might tell you some information. I am not sure what to do here, the errors are very vague.

**Comment by axetang** [comment]
Hi All,
We found the method to solve the issues.
Install node.js 8.11.4
Use cnpm replace npm by the following command
npm install -g cnpm --registry=https://registry.npm.taobao.org
cnpm install
./setupFabricNetwork.sh
In step 4, errors occur. Study the errors and you will find that the errors occurred in the process of chaincode instantiation. Then try to do it mannualy
docker exec -it cli bash
peer chaincode instantiate -o orderer.example.com:7050 --tls $CORE_PEER_TLS_ENABLED --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem -C mychannel -n mycc -v v0 -c '{"Args":[]}' -P "OR('Org1MSP.member','Org2MSP.member')"
now use “docker ps”, you could find that the chaincode image which means that the instantiation success.
finally you can use the following url to visit the application.
localhost:4000/ng/src
 
comment: you must remove the directory ‘ node_modules’ before you use ‘cnpm install’.
 
 
BR,
AXE

**Comment by axetang** [comment]
Hi All,
We found the method to solve the issues.

1.  Install node.js 8.11.4
2. Use cnpm replace npm by the following command
       npm install -g cnpm --registry=https://registry.npm.taobao.org
3. cnpm install
4.    ./setupFabricNetwork.sh
5. In step 4, errors occur. Study the errors and you will find that the errors occurred in the process of chaincode instantiation. Then try to do it mannualy
6. docker exec -it cli bash
7. peer chaincode instantiate -o orderer.example.com:7050 --tls $CORE_PEER_TLS_ENABLED --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem -C mychannel -n mycc -v v0 -c '{"Args":[]}' -P "OR('Org1MSP.member','Org2MSP.member')"
8. now use “docker ps”, you could find that the chaincode image which means that the instantiation success.
9. finally you can use the following url to visit the application.
        localhost:4000/ng/src
 
comment: you must remove the directory ‘ node_modules’ before you use ‘cnpm install’.
 
 
BR,
AXE

1.

**Comment by vanipolnedi** [comment]
cmd: **docker logs web**
> cross-env NODE_ENV=production&&node ./bin/server

/app/app/static/js
Server running on port: 3000
Default channel not found, attempting creation...
Successfully created a new default channel.
Joining peers to the default channel.
Chaincode is not installed, attempting installation...
Base container image present.
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
info: [packager/Golang.js]: packaging GOLANG from bcins
Successfully installed chaincode on the default channel.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: API error (404): {"message":"network build-blockchain-insurance-app_default not found"}

    at new createStatusError (/app/node_modules/grpc/src/client.js:64:15)
    at /app/node_modules/grpc/src/client.js:583:15
Fatal error instantiating chaincode on some(all) peers!
Error: Proposal rejected by some (all) of the peers: Error: 2 UNKNOWN: error starting container: API error (404): {"message":"network build-blockchain-insurance-app_default not found"}

    at /app/www/blockchain/utils.js:248:15
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/utils.js:102:191)
    at /app/bin/blockchain/utils.js:102:361
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production&&node ./bin/server`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the blockchain-for-insurance@2.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-13T05_35_28_904Z-debug.log

and

**cmd : docker ps** 

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                              NAMES
579f29f7a912        police-peer         "peer node start"        10 minutes ago      Up 10 minutes       0.0.0.0:10051->7051/tcp, 0.0.0.0:10053->7053/tcp   police-peer
4f1c9ecd0787        repairshop-peer     "peer node start"        10 minutes ago      Up 10 minutes       0.0.0.0:9051->7051/tcp, 0.0.0.0:9053->7053/tcp     repairshop-peer
eed3f945e91d        shop-peer           "peer node start"        10 minutes ago      Up 10 minutes       0.0.0.0:8051->7051/tcp, 0.0.0.0:8053->7053/tcp     shop-peer
2df2dbb9f081        insurance-peer      "peer node start"        10 minutes ago      Up 10 minutes       0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp     insurance-peer
15ade607c484        police-ca           "fabric-ca-server st…"   10 minutes ago      Up 10 minutes       0.0.0.0:10054->7054/tcp                            police-ca
8d5e36b8b878        shop-ca             "fabric-ca-server st…"   10 minutes ago      Up 10 minutes       0.0.0.0:8054->7054/tcp                             shop-ca
3c6ebd525e7e        insurance-ca        "fabric-ca-server st…"   10 minutes ago      Up 10 minutes       0.0.0.0:7054->7054/tcp                             insurance-ca
425d2bcc7795        repairshop-ca       "fabric-ca-server st…"   10 minutes ago      Up 10 minutes       0.0.0.0:9054->7054/tcp                             repairshop-ca
10b1f054344c        orderer             "orderer"                10 minutes ago      Up 10 minutes       0.0.0.0:7050->7050/tcp  

any suggestions please??

**Comment by ljbennett62** [comment]
pattern is updated so issue went away
