### ISSUE TITLE
Channel does not exist

### ISSUE THREAD

**Issue by newTypeGeek** [IBM/build-blockchain-insurance-app#48]
I have built the network with command `./build_ubuntu.sh`. Using the command `docker logs web` to check the status installation gives the following error.

    error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: channel does not exist: default
        at new createStatusError (/app/node_modules/grpc/src/client.js:64:15)
        at /app/node_modules/grpc/src/client.js:583:15
    error: [Channel.js]: Failed Query channel info. Error: Error: 2 UNKNOWN: channel does not exist: default
        at new createStatusError (/app/node_modules/grpc/src/client.js:64:15)
        at /app/node_modules/grpc/src/client.js:583:15
    (node:23) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
        at /app/www/routers/shop.router.js:49:19
        at Generator.next (<anonymous>)
        at step (/app/bin/routers/shop.router.js:20:191)
        at /app/bin/routers/shop.router.js:20:361
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

If I continue to follow the tutorial with localhost:3000 to buy a bike, I am stuck at ordering the bike with `Processing Transaction...` keeps loading.

**Comment by Akakandelwa** [comment]
I suspect this issue is related to issue #45.

See this: #45 (comment)

**Comment by sblisztomaniac** [comment]
@newTypeGeek  did u find any solution to this problem mate?

**Comment by ljbennett62** [comment]
pattern is updated - so issue went away
