### ISSUE TITLE
Help !

### ISSUE THREAD

**Issue by vkkan** [IBM/build-blockchain-insurance-app#49]
First of all thanks for the detailed note on how to install and bring up the application. I have quick question that lets say if I want to make any changes on insurance.router.js , that change will get updated instantly or do i have to run ./build_ubuntu.sh ? since most of my nodejs experience I have used gulp on my environment which does autoupdate for me.

Highly appreciated the help

**Comment by hovig** [comment]
@vkkan  - any change you make it will reflect back on your project but just make sure you clean up the previous containers to avoid confusions
