### ISSUE TITLE
Can't start web service with error "failed to enroll user"

### ISSUE THREAD

**Issue by hughhuangzh** [IBM/build-blockchain-insurance-app#55]
Hi, I can't start my web service with below issue:

> blockchain-for-insurance@2.1.0 serve /app
> cross-env NODE_ENV=production&&node ./bin/server

/app/app/static/js
Server running on port: 3000
Failed to enroll user. Error: Could not get UserContext! Error: Failed to enroll and persist User. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.0.247:7054]
Fatal error logging into blockchain organization clients!
Error: Could not get UserContext! Error: Failed to enroll and persist User. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.0.247:7054]
    at /app/www/blockchain/utils.js:444:11
    at Generator.throw (<anonymous>)
    at step (/app/bin/blockchain/utils.js:102:191)
    at /app/bin/blockchain/utils.js:102:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production&&node ./bin/server`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the blockchain-for-insurance@2.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

anyone can help?

**Comment by Harshmakadia** [comment]
Facing the same issue. Is there any solution to fix this?

**Comment by ljbennett62** [comment]
pattern is getting updated - so issue went away
