### ISSUE TITLE
getting error while running bash file.

### ISSUE THREAD

**Issue by vishalpatelvc** [IBM/build-blockchain-insurance-app#58]
while running build_ubuntu.sh file I am getting this error.

_ERROR: pull access denied for insurance-ca, repository does not exist or may require 'docker login'
Pulling insurance-ca (insurance-ca:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing._

**Comment by hovig** [comment]
@vishalpatelvc - couple things:

* run `docker login` and put your Docker credentials
* run `./clean.sh` to get rid of existing images and containers and then run it with `./build_*.sh`. 
* The project is updated with the latest fabric now

**Comment by vishalpatelvc** [comment]
Thank you.

**Comment by sblisztomaniac** [comment]
> while running build_ubuntu.sh file I am getting this error.
> 
> _ERROR: pull access denied for insurance-ca, repository does not exist or may require 'docker login' Pulling insurance-ca (insurance-ca:)... ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing._

I have the same issue even after cleaning and rebuilding, did it work for you?

**Comment by shreychaturvedi123** [comment]
`Status: Image is up to date for hyperledger/fabric-ccenv:latest
docker.io/hyperledger/fabric-ccenv:latest
===> Pulling fabric ca Image
==> FABRIC CA IMAGE

Error response from daemon: manifest for hyperledger/fabric-ca:latest not found: manifest unknown: manifest unknown
Pulling insurance-ca (insurance-ca:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.`

I am still facing same issue after trying above steps?
