### ISSUE TITLE
Websocket errors

### ISSUE THREAD

**Issue by gsomapoornan** [IBM/build-blockchain-insurance-app#59]
I am getting below socket errors when communication is initiated between different web apps. I have deployed the app on Azure box. Tried adding web.config file in root. Not much luck.
GET http://bcins.eastus.cloudapp.azure.com:3000/socket.io/?EIO=3&transport=polling&t=MXRQHCL net::ERR_CONNECTION_REFUSED

**Comment by hovig** [comment]
@gsomapoornan - the web app still need some work but it will run normal and the project is also updated with the latest fabric sdk and the web app is running on `localhost:3000`. I will close this issue. Let us know if you face the same issue with the latest changes.
