### ISSUE TITLE
failed to start Web and localhost:3000 failed to connect

### ISSUE THREAD

**Issue by rajiv180984** [IBM/build-blockchain-insurance-app#6]
Please help me to run this application. For me all docker image build successfully for this application.
[./build.sh completed successfully without any issue.]
Docker compose also worked fine without any issue or warning.
But I am gettinng error to start web -server.
**I ran command "docker logs web" and getting following error.**
root@rajeev-VirtualBox:/usr/local/IBM_Blockchain/build-blockchain-insurance-app# docker logs web
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.3
npm info lifecycle blockchain-for-insurance@2.1.0preserve: blockchain-for-insurance@2.1.0
npm info lifecycle blockchain-for-insurance@2.1.0serve: blockchain-for-insurance@2.1.0

blockchain-for-insurance@2.1.0 serve /app
cross-env NODE_ENV=production node ./bin/server
fs.js:642
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
^

Error: ENOENT: no such file or directory, open '/app/certs/ordererOrg.pem'
at Error (native)
at Object.fs.openSync (fs.js:642:18)
at fs.readFileSync (fs.js:510:33)
at readCryptoFile (/app/bin/blockchain/config.js:13:57)
at Object. (/app/bin/blockchain/config.js:23:10)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

npm info lifecycle blockchain-for-insurance@2.1.0~serve: Failed to exec serve script
npm ERR! Linux 4.4.0-109-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v6.11.3
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockchain-for-insurance@2.1.0 serve: cross-env NODE_ENV=production node ./bin/server
npm ERR! Exit status 1

Big Thanks to look into issue and suggestion.

**Comment by roysom007** [comment]
I am also facing same issue.
Could anyone please help on this ...

Thanks in advance

**Comment by roysom007** [comment]
hey,

Got a solution from below URL 
https://github.com/IBM/build-blockchain-insurance-app/issues/3

Try clone this fork link - https://github.com/rslu2000/build-blockchain-insurance-app

**Comment by linghanweiyu** [comment]
I fork link  - https://github.com/rslu2000/build-blockchain-insurance-app,
I ran command "docker logs web" and getting following error.
info: [EventHub.js]: _connect - options {"grpc.ssl_target_name_override":"insurance-peer","grpc.default_authority":"insurance-peer"}
Failed to configure event hubs. Error Cannot read property 'getConnectivityState' of undefined
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'getConnectivityState' of undefined
/app/node_modules/fabric-client/lib/EventHub.js:305
			if(self._stream) state = self._stream.call.channel_.getConnectivityState();
			                                                   ^

TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/app/node_modules/fabric-client/lib/EventHub.js:305:55)
    at emitOne (events.js:96:13)
    at ClientDuplexStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ClientDuplexStream.Readable.push (_stream_readable.js:134:10)
    at Object.onReceiveMessage (/app/node_modules/grpc/src/client_interceptors.js:1302:19)
    at InterceptingListener.recvMessageWithContext (/app/node_modules/grpc/src/client_interceptors.js:629:19)
    at /app/node_modules/grpc/src/client_interceptors.js:728:14

npm info lifecycle blockchain-for-insurance@2.1.0~serve: Failed to exec serve script
npm ERR! Linux 3.10.0-514.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production node ./bin/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blockchain-for-insurance@2.1.0 serve script 'cross-env NODE_ENV=production node ./bin/server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blockchain-for-insurance package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node ./bin/server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blockchain-for-insurance
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blockchain-for-insurance
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

**Comment by patrickodhiambo** [comment]
Also getting similar error. Anyone with a solution on this?

info: [EventHub.js]: _connect - options {"grpc.ssl_target_name_override":"insurance-peer","grpc.default_authority":"insurance-peer"}
Failed to configure event hubs. Error Cannot read property 'getConnectivityState' of undefined
(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'getConnectivityState' of undefined
/app/node_modules/fabric-client/lib/EventHub.js:305
                        if(self._stream) state = self._stream.call.channel_.getConnectivityState();
                                                                           ^

TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/app/node_modules/fabric-client/lib/EventHub.js:305:55)
    at emitOne (events.js:96:13)
    at ClientDuplexStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ClientDuplexStream.Readable.push (_stream_readable.js:134:10)
    at Object.onReceiveMessage (/app/node_modules/grpc/src/client_interceptors.js:1302:19)
    at InterceptingListener.recvMessageWithContext (/app/node_modules/grpc/src/client_interceptors.js:629:19)
    at /app/node_modules/grpc/src/client_interceptors.js:728:14

npm info lifecycle blockchain-for-insurance@2.1.0~serve: Failed to exec serve script
npm ERR! Linux 4.4.0-116-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! blockchain-for-insurance@2.1.0 serve: `cross-env NODE_ENV=production node ./bin/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blockchain-for-insurance@2.1.0 serve script 'cross-env NODE_ENV=production node ./bin/server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blockchain-for-insurance package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node ./bin/server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blockchain-for-insurance
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blockchain-for-insurance
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

**Comment by linghanweiyu** [comment]
@lengyijun My system is centeOS. I don't know is it a reson
