### ISSUE TITLE
while checking docker logs, getting this error

### ISSUE THREAD

**Issue by abhinavgrg074** [IBM/build-blockchain-insurance-app#61]
blockchain-for-insurance@2.1.1 serve /app
> cross-env NODE_ENV=production&&node ./bin/server

/app/app/static/js
Server running on port: 3000
Failed to configure event hubs. Error this._channelName.newChannelEventHub is not a function
(node:22) UnhandledPromiseRejectionWarning: TypeError: this._channelName.newChannelEventHub is not a function
    at OrganizationClient.initEventHubs (/app/www/blockchain/utils.js:77:49)
    at /app/www/blockchain/setup.js:89:19
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/setup.js:27:191)
    at /app/bin/blockchain/setup.js:27:361
    at <anonymous>
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hovig** [comment]
check here -> [Failed to configure event hub error #62](https://github.com/IBM/build-blockchain-insurance-app/issues/62)
