### ISSUE TITLE
Failed to configure event hub error

### ISSUE THREAD

**Issue by sblisztomaniac** [IBM/build-blockchain-insurance-app#62]
sanket@sanket-bojewar:~/build-blockchain-insurance-app$ docker logs web

> blockchain-for-insurance@2.1.1 serve /app
> cross-env NODE_ENV=production&&node ./bin/server

/app/app/static/js
Server running on port: 3000
Failed to configure event hubs. Error this._channelName.newChannelEventHub is not a function
(node:22) UnhandledPromiseRejectionWarning: TypeError: this._channelName.newChannelEventHub is not a function
    at OrganizationClient.initEventHubs (/app/www/blockchain/utils.js:77:49)
    at /app/www/blockchain/setup.js:89:19
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/setup.js:27:191)
    at /app/bin/blockchain/setup.js:27:361
    at <anonymous>
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by plachira** [comment]
I am also facing this same issue

**Comment by hovig** [comment]
i just cloned and ran the code - the app is up and running. 

Few tips to try:

- make sure you clone the latest repo from github

- what version of python do you have installed on your machine? or the readme to make sure you have the latest versions

- did you remove all previously installed images/containers? do it manually if you have to:
`docker rm $(docker ps -aq) -f`
`docker rmi $(docker images -aq) -f`
Then try `docker ps` and `docker images` to make sure you got rid of them before starting to install the app by running `./build_mac.sh` or whatever machine you have.

Let me know how it goes.

**Comment by sblisztomaniac** [comment]
Can you please post your versions of the prerequisite mentioned in the readme? Thanks alot for your support.

**Comment by sblisztomaniac** [comment]
> i just cloned and ran the code - the app is up and running.
> 
> Few tips to try:
> 
> * make sure you clone the latest repo from github
> * what version of python do you have installed on your machine? or the readme to make sure you have the latest versions
> * did you remove all previously installed images/containers? do it manually if you have to:
>   `docker rm $(docker ps -aq) -f`
>   `docker rmi $(docker images -aq) -f`
>   Then try `docker ps` and `docker images` to make sure you got rid of them before starting to install the app by running `./build_mac.sh` or whatever machine you have.
> 
> Let me know how it goes.

**Comment by khizir97** [comment]
> i just cloned and ran the code - the app is up and running.
> 
> Few tips to try:
> 
>     * make sure you clone the latest repo from github
> 
>     * what version of python do you have installed on your machine? or the readme to make sure you have the latest versions
> 
>     * did you remove all previously installed images/containers? do it manually if you have to:
>       `docker rm $(docker ps -aq) -f`
>       `docker rmi $(docker images -aq) -f`
>       Then try `docker ps` and `docker images` to make sure you got rid of them before starting to install the app by running `./build_mac.sh` or whatever machine you have.
> 
> 
> Let me know how it goes.

python -V
Python 2.7.15rc1

 python2 -V
Python 2.7.15rc1

 python3 -V
Python 3.6.7


performed both the steps, still isn't working.

**Comment by plachira** [comment]
> i just cloned and ran the code - the app is up and running.
> 
> Few tips to try:
> 
> * make sure you clone the latest repo from github
> * what version of python do you have installed on your machine? or the readme to make sure you have the latest versions
> * did you remove all previously installed images/containers? do it manually if you have to:
>   `docker rm $(docker ps -aq) -f`
>   `docker rmi $(docker images -aq) -f`
>   Then try `docker ps` and `docker images` to make sure you got rid of them before starting to install the app by running `./build_mac.sh` or whatever machine you have.
> 
> Let me know how it goes.

If I clone 1 commit before, it work. Somehow the latest commit (updated to the latest fabric version) is having issues. Example, `const defaultEventHub = this._channelName.newChannelEventHub(this._peerConfig);` should have been `const defaultEventHub = this._channel.newChannelEventHub(this._peerConfig);`. There are similar errors.

**Comment by khizir97** [comment]
> should have been `const defaultEventHub = this._channel.newChannelEventHub(this._peerConfig);`

which file?
which line?
does it work after the change?

**Comment by khizir97** [comment]
> If I clone 1 commit before, it work

the previous commit works just fine.

- just in case someone needs a way to use a specific commit

1. do a regular git clone where you want the repo (gets everything to date — I know, not what is wanted, we're getting there)
2. git checkout <commit tag> of the commit you want

**Comment by sblisztomaniac** [comment]
Can you type in the command to use the commit which is working fine? Thank
you.

**Comment by sblisztomaniac** [comment]
> > If I clone 1 commit before, it work
> 
> the previous commit works just fine.
> 
> * just in case someone needs a way to use a specific commit
> 
> 1. do a regular git clone where you want the repo (gets everything to date — I know, not what is wanted, we're getting there)
> 2. git checkout  of the commit you want


can you type in the git checkout command of the commit which is working fine?

**Comment by khizir97** [comment]
> can you type in the git checkout command of the commit which is working fine?


----- /build-blockchain-insurance-app# git checkout d9de332d88a798094a1c256041d953bb843add35


Note: checking out 'd9de332d88a798094a1c256041d953bb843add35'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d9de332 Update README.md

**Comment by hovig** [comment]
if you clone 1 commit before, you're cloning a repo with previous fabric version and not **1.4**. the latest version supports `ChannelEventHub` library and not `EventHub`

**Comment by sblisztomaniac** [comment]
> if you clone 1 commit before, you're cloning a repo with previous fabric version and not **1.4**. the latest version supports `ChannelEventHub` library and not `EventHub`

Can you please post your version of the prerequisites mentioned in the readme? Thanks alot for your support.

**Comment by hovig** [comment]
Docker - 18.09.2
Docker Compose - 1.21.2
node - 11.11.0
Git client - 2.19.1
Python - 3.5.5 on one machine and 2.7.x on another (tested on both)

**Comment by dangtuan21** [comment]
Hi. It did not work with the master branch. It worked with `d9de332`

**Comment by plachira** [comment]
I have opened a pull request to fix the issue in the latest commit. #66

**Comment by sblisztomaniac** [comment]
> Docker - 18.09.2
> Docker Compose - 1.21.2
> node - 11.11.0
> Python - 3.5.5 on one machine and 2.7.x on another (tested on both)



Sankets-MacBook-Pro:build-blockchain-insurance-app sanket$ python --version
Python 3.7.1
Sankets-MacBook-Pro:build-blockchain-insurance-app sanket$ docker --version
Docker version 18.09.2, build 6247962
Sankets-MacBook-Pro:build-blockchain-insurance-app sanket$ docker-compose --version
docker-compose version 1.23.2, build 1110ad01
Sankets-MacBook-Pro:build-blockchain-insurance-app sanket$ node --version
v11.11.0
Sankets-MacBook-Pro:build-blockchain-insurance-app sanket$ git --version
git version 2.20.1
Sankets-MacBook-Pro:build-blockchain-insurance-app sanket$ docker logs web

> blockchain-for-insurance@2.1.1 serve /app
> cross-env NODE_ENV=production&&node ./bin/server

/app/app/static/js
Server running on port: 3000
Failed to configure event hubs. Error this._channelName.newChannelEventHub is not a function
(node:22) UnhandledPromiseRejectionWarning: TypeError: this._channelName.newChannelEventHub is not a function
    at OrganizationClient.initEventHubs (/app/www/blockchain/utils.js:77:49)
    at /app/www/blockchain/setup.js:89:19
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/setup.js:27:191)
    at /app/bin/blockchain/setup.js:27:361
    at <anonymous>
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.



tried but the same error.

**Comment by sblisztomaniac** [comment]
> > i just cloned and ran the code - the app is up and running.
> > Few tips to try:
> > 
> > * make sure you clone the latest repo from github
> > * what version of python do you have installed on your machine? or the readme to make sure you have the latest versions
> > * did you remove all previously installed images/containers? do it manually if you have to:
> >   `docker rm $(docker ps -aq) -f`
> >   `docker rmi $(docker images -aq) -f`
> >   Then try `docker ps` and `docker images` to make sure you got rid of them before starting to install the app by running `./build_mac.sh` or whatever machine you have.
> > 
> > Let me know how it goes.
> 
> If I clone 1 commit before, it work. Somehow the latest commit (updated to the latest fabric version) is having issues. Example, `const defaultEventHub = this._channelName.newChannelEventHub(this._peerConfig);` should have been `const defaultEventHub = this._channel.newChannelEventHub(this._peerConfig);`. There are similar errors.

I tried the previous commit, it ran for sometime then it began to give me error/issue #45 ,any help would be appreciated.

**Comment by sblisztomaniac** [comment]
> Hi. It did not work with the master branch. It worked with `d9de332`

is it still working?

**Comment by dangtuan21** [comment]
Yes it is

**Comment by sblisztomaniac** [comment]
> > Hi. It did not work with the master branch. It worked with `d9de332`
> 
> is it still working?

Thank you for letting me know, are you using all the latest prerequisites?

**Comment by dangtuan21** [comment]
Yes, I am

**Comment by plachira** [comment]
Can you try again? It should now work.

**Comment by JosephChan101** [comment]
The demo was updated two days ago, I tried it this afternoon and found it not working as expected. Looking into the docker logs web I found that peers failed to join the channel and an error message that network not found: build-blockchain-insurance-app_default not found. I checked the docker network and found the buildblockchaininsuranceappmaster_default network. So I went into the peer-base.yaml,  changed '- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=build-blockchain-insurance-app_default' to '- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=buildblockchaininsuranceappmaster_default', and relaunched it. It worked then.

**Comment by plachira** [comment]
> The demo was updated two days ago, I tried it this afternoon and found it not working as expected. Looking into the docker logs web I found that peers failed to join the channel and an error message that network not found: build-blockchain-insurance-app_default not found. I checked the docker network and found the buildblockchaininsuranceappmaster_default network. So I went into the peer-base.yaml, changed '- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=build-blockchain-insurance-app_default' to '- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=buildblockchaininsuranceappmaster_default', and relaunched it. It worked then.

You can do either of these two:

- Main folder name to be build-blockchain-insurance-app
- Create a .env file with COMPOSE_PROJECT_NAME=build-blockchain-insurance-app

My understanding is that Docker Compose creates default network in this syntax.

Let us know if this works.

**Comment by plachira** [comment]
> I am also facing this same issue

This issue is solved with my latest commit. Can we get this closed?

**Comment by sblisztomaniac** [comment]
> > I am also facing this same issue
> 
> This issue is solved with my latest commit. Can we get this closed?

**Comment by sblisztomaniac** [comment]
> > > I am also facing this same issue
> > 
> > 
> > This issue is solved with my latest commit. Can we get this closed?

<img width="1280" alt="error" src="https://user-images.githubusercontent.com/29702480/55230762-c357a480-5246-11e9-9d38-ba1d6b324a07.png">


Can you please help me with this?

**Comment by plachira** [comment]
> > > > I am also facing this same issue
> > > 
> > > 
> > > This issue is solved with my latest commit. Can we get this closed?
> 
> <img alt="error" width="1280" src="https://user-images.githubusercontent.com/29702480/55230762-c357a480-5246-11e9-9d38-ba1d6b324a07.png">
> 
> This was the error while building,Can you please help me with this?



> > > > I am also facing this same issue
> > > 
> > > 
> > > This issue is solved with my latest commit. Can we get this closed?
> 
> <img alt="error" width="1280" src="https://user-images.githubusercontent.com/29702480/55230762-c357a480-5246-11e9-9d38-ba1d6b324a07.png">
> 
> This was the error while building,Can you please help me with this?

Try `./clean.sh`
