### ISSUE TITLE
Is this application can deploy on IBP free 2.0

### ISSUE THREAD

**Issue by ayiyaliing** [IBM/build-blockchain-insurance-app#67]
Q1: I notice this application is deployed on local  environment that is created by docker image. is it supported to connect with exist IBP network but not on local docker environment? (for example, IBP free 2.0),
Q2: anyway,  the insurance app code run on docker image of web , it read the config (build-blockchain-insurance-app/web/www/blockchain/config.js)come from local config, could I use application for other existing network? now I don't find the way except modify the code by myself? 
please help, thanks

**Comment by ljbennett62** [comment]
@ayiyaliing - yes - and I have a developer who is updating it to show how to run it on the IBP V2.0 network.  I don't quite understand your second question - are you asking can you deploy it on another network that you have set up - I don't see why not.

**Comment by aelhadi** [comment]
Hi,

Any update on how to run it on IBP V2.0?

Thanks

**Comment by ljbennett62** [comment]
@aelhadi - did you see the latest release - it is on IBP V2.0
