### ISSUE TITLE
Application run failed - I get the following error in 'docker logs web'

### ISSUE THREAD

**Issue by saiv94** [IBM/build-blockchain-insurance-app#69]
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! blockchain-for-insurance@2.1.1 serve: `cross-env NODE_ENV=production && node ./bin/server`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the blockchain-for-insurance@2.1.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-30T11_16_32_198Z-debug.log

###########Please help

**Comment by saiv94** [comment]
I think the repository misses ./bin/server files? Issue persists!!!

**Comment by DeepRoy683** [comment]
any fixes available, please...same error me too!

**Comment by DeepRoy683** [comment]
open peer-base.yaml and set 
- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=build-blockchain-insurance-app_default
It worked for me

**Comment by flome** [comment]
For me it worked with removing the dashes in the default network name as docker seems to create the network using the parent folder name if no network is specified. To my understanding, older versions of docker do not support dashes in the name. Therefore, for me

    CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=buildblockchaininsuranceapp_default
    
fixed the issue

**Comment by flome** [comment]
> 
> 
> open peer-base.yaml and set
> 
>     * CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=build-blockchain-insurance-app_default
>       It worked for me

If this solved it for you, I think you updated docker-compose somewhere on the way?

**Comment by vaibhavr2709** [comment]
Its because of an older version of docker compose. I fixed it by upgrading it. 
`sudo apt-get remove docker-compose
VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | jq .name -r)
DESTINATION=/usr/local/bin/docker-compose
sudo curl -L https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m) -o $DESTINATION
sudo chmod 755 $DESTINATION
`
Now run the bash file again

**Comment by vaibhavr2709** [comment]
Hey @saiv94 refer issue #79 and you'll be good to go.

**Comment by ljbennett62** [comment]
@saiv94 - this pattern has been re-written to use the IBM Blockchain Platform - please try this version
