### ISSUE TITLE
 Failed to fetch

### ISSUE THREAD

**Issue by rezaprimasatya** [IBM/build-blockchain-insurance-app#71]
Fetched 10.1 MB in 10s (988 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.

![Screen Shot 2019-04-16 at 09 59 30 (2)](https://user-images.githubusercontent.com/4263809/56179101-c1575900-602e-11e9-9f08-c44a2273acfd.png)

**Comment by DeepRoy683** [comment]
check issue #68

**Comment by ljbennett62** [comment]
@DeepRoy683 - upgraded this to use IBM Blockchain Platform - please try this version of the pattern
