### ISSUE TITLE
Ubuntu build is not working.

### ISSUE THREAD

**Issue by Rohit-shopasky** [IBM/build-blockchain-insurance-app#74]
ERROR: pull access denied for shop-ca, repository does not exist or may require 'docker login'

**Comment by DeepRoy683** [comment]
try #68

**Comment by varunagarwal315** [comment]
I am getting an issue that says enrollment functions in CA could not be called and in `docker logs web` it shows
```
Error: Proposal rejected by some (all) of the peers: Error: error starting container: error starting container: API error (404): network build-blockchain-insurance-app_default not found
    at /app/www/blockchain/utils.js:243:15
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/utils.js:102:191)
    at /app/bin/blockchain/utils.js:102:361
    at <anonymous>
```

**Comment by vaibhavr2709** [comment]
Refer #79 and you'll be good to go. If it works don't forget to close the issue.

**Comment by ljbennett62** [comment]
@Rohit-shopasky - also try out this new version of the pattern using the IBM Blockchain Platform.

**Comment by kambelkouame** [comment]
please i need help !! i have the same probleme that @Rohit-shopasky 
dockerfile 

FROM docker.io/library/node:8.11.3

ENV NODE_ENV production
ENV PORT 3000
ENV DOCKER_SOCKET_PATH /host/var/run/docker.sock
ENV DOCKER_CCENV_IMAGE hyperledger/fabric-ccenv:latest

RUN mkdir /app
COPY . /app
WORKDIR /app

RUN npm i && npm i --only=dev \
    && npm run build \
    && npm prune

EXPOSE 3000
CMD ["npm", "run", "serve"]


peer-base.yaml

version: '2'

services:
  peer-base:
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=buildblockchaininsuranceapp_default
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_ENDORSER_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_MSPCONFIGPATH=/peer/crypto/msp
    - CORE_PEER_TLS_CERT_FILE=/peer/crypto/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/peer/crypto/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/peer/crypto/tls/ca.crt
    working_dir: /peer
    command: peer node start
    volumes:
    - /var/run/:/host/var/run/


ERROR:
The command '/bin/sh -c npm i && npm i --only=dev     && npm run build     && npm prune' returned a non-zero code: 1
Pulling shop-ca (shop-ca:latest)...
ERROR: pull access denied for shop-ca, repository does not exist or may require 'docker login'




@Rohit-shopasky @DeepRoy683 @varunagarwal315 @ljbennett62 @vaibhavr2709

**Comment by kambelkouame** [comment]
now my docker logs web 

> blockchain-for-insurance@2.1.1 serve /app
> cross-env NODE_ENV=production&&node ./bin/server

Wallet path: /app/www/blockchain/wallet
/app/app/static/js
Server running on port: 3000
Default channel not found, attempting creation...
Successfully created a new default channel.
Joining peers to the default channel.
Peer joined default channel
Peer joined default channel
Peer joined default channel
Peer joined default channel
Connecting and Registering Block Events
Chaincode is not installed, attempting installation...
Base container image present.

**Comment by vaibhavr2709** [comment]
> now my docker logs web
> 
> > blockchain-for-insurance@2.1.1 serve /app
> > cross-env NODE_ENV=production&&node ./bin/server
> 
> Wallet path: /app/www/blockchain/wallet
> /app/app/static/js
> Server running on port: 3000
> Default channel not found, attempting creation...
> Successfully created a new default channel.
> Joining peers to the default channel.
> Peer joined default channel
> Peer joined default channel
> Peer joined default channel
> Peer joined default channel
> Connecting and Registering Block Events
> Chaincode is not installed, attempting installation...
> Base container image present.

This is incomplete log. Wait for some time and then run the command again. It takes some time to install and instantiate the chaincode. The log you are mentioning here is alright
