### ISSUE TITLE
throw new Error('"peer" parameter is missing')

### ISSUE THREAD

**Issue by emassaad** [IBM/build-blockchain-insurance-app#78]
Hello,

I am using Ubuntu 18 and the build script finishes successfully however upon checking docker logs web, i can see the below error:
root@ubuntu:~# docker logs web

> blockchain-for-insurance@2.1.1 serve /app
> cross-env NODE_ENV=production&&node ./bin/server

/app/node_modules/fabric-client/lib/Channel.js:1886
                        throw new Error('"peer" parameter is missing');
                        ^

Error: "peer" parameter is missing
    at Channel._getPeerForEvents (/app/node_modules/fabric-client/lib/Channel.js:1886:10)
    at Channel.newChannelEventHub (/app/node_modules/fabric-client/lib/Channel.js:321:15)
    at new OrganizationClient (/app/bin/blockchain/utils.js:138:43)
    at Object.<anonymous> (/app/bin/blockchain/setup.js:33:25)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blockchain-for-insurance@2.1.1 serve: `cross-env NODE_ENV=production&&node ./bin/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blockchain-for-insurance@2.1.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-08T12_54_29_350Z-debug.log
root@ubuntu:~#

Can you please advise
Thank you
B.R
Elias

**Comment by horeaporutiu** [comment]
@emassaad are you able to run the web-app, or is this error preventing you from running the app?

**Comment by emassaad** [comment]
Hello horeaporutiu,
i am not able to run the app, the error is preventing me from running the app.

Now i switched to ubuntu 16,04 as recommended, and i am not able to build the setup as per following:
 
Login Succeeded
root@HP:~/build-blockchain-insurance-app# ./build_ubuntu.sh 

#################################################################
#######        Generating cryptographic material       ##########
#################################################################
/root/build-blockchain-insurance-app/cryptogen: 1: /root/build-blockchain-insurance-app/cryptogen: ELF: not found
/root/build-blockchain-insurance-app/cryptogen: 7: /root/build-blockchain-insurance-app/cryptogen: Syntax error: ";;" unexpected (expecting ")")
===> Pulling fabric Images
==> FABRIC IMAGE: peer

latest: Pulling from hyperledger/fabric-peer
no matching manifest for unknown in the manifest list entries
./build_ubuntu.sh: line 7: docker-compose: command not found
root@HP:~/build-blockchain-insurance-app#

**Comment by emassaad** [comment]
Hello,

After installing docker-compose, a new error is seen:

root@HP:~/build-blockchain-insurance-app# ./build_ubuntu.sh 

#################################################################
#######        Generating cryptographic material       ##########
#################################################################
/root/build-blockchain-insurance-app/cryptogen: 1: /root/build-blockchain-insurance-app/cryptogen: ELF: not found
/root/build-blockchain-insurance-app/cryptogen: 7: /root/build-blockchain-insurance-app/cryptogen: Syntax error: ";;" unexpected (expecting ")")
===> Pulling fabric Images
==> FABRIC IMAGE: peer

latest: Pulling from hyperledger/fabric-peer
no matching manifest for unknown in the manifest list entries
Creating network "buildblockchaininsuranceapp_default" with the default driver
Pulling shop-ca (shop-ca:latest)...
ERROR: pull access denied for shop-ca, repository does not exist or may require 'docker login'

**Comment by horeaporutiu** [comment]
@emassaad 

Hmm, okay. you have done `docker login` right?

**Comment by emassaad** [comment]
yes i logged in via docker

**Comment by horeaporutiu** [comment]
Ok - let me test this and try to re-create the problem. I'll comment again once I find something.

**Comment by horeaporutiu** [comment]
@emassaad are you able to see any fixes in this thread? Making those small changes in the dockerfile may be the solution - https://github.com/IBM/build-blockchain-insurance-app/issues/68

**Comment by emassaad** [comment]
Hi,

I tried the workaround on the Dockerfile as per below:
FROM ubuntu:trusty
RUN apt update && apt install -y build-essential
FROM node:8.11-stretch

ENV NODE_ENV production
ENV PORT 3000
ENV DOCKER_SOCKET_PATH /host/var/run/docker.sock
ENV DOCKER_CCENV_IMAGE hyperledger/fabric-ccenv:latest

RUN mkdir /app
COPY . /app
WORKDIR /app

RUN npm i && npm i --only=dev
&& npm run build
&& npm prune
&& apt remove -y build-essential

EXPOSE 3000
CMD ["npm", "run", "serve"]

but it is still the same, any suggestion please, could it be related to missing library files ?

**Comment by horeaporutiu** [comment]
try this dockerfile:

FROM docker.io/library/node:8.11.3

ENV NODE_ENV production
ENV PORT 3000
ENV DOCKER_SOCKET_PATH /host/var/run/docker.sock
ENV DOCKER_CCENV_IMAGE hyperledger/fabric-ccenv:latest

RUN mkdir /app
COPY . /app
WORKDIR /app

RUN npm i && npm i --only=dev 
&& npm run build 
&& npm prune

EXPOSE 3000
CMD ["npm", "run", "serve"]

Any luck?

**Comment by emassaad** [comment]
Hello Hoera,

Sorry for the late reply, actually my problem was solved by switching from Ubuntu i386 to i686, and it is running ok.
However upon restarting the laptop i am not able to open the GUI anymore localhost:3000
Any advise please?

Thank you for your continuous support @horeaporutiu 
B.R
Elias

**Comment by emassaad** [comment]
Thanks Hoera, issue solved
