### ISSUE TITLE
Chaincode not instantiating on ubuntu build

### ISSUE THREAD

**Issue by vaibhavr2709** [IBM/build-blockchain-insurance-app#79]
> blockchain-for-insurance@2.1.1 serve /app
 cross-env NODE_ENV=production&&node ./bin/server
Wallet path: /app/www/blockchain/wallet
/app/app/static/js
Server running on port: 3000
Default channel not found, attempting creation...
Successfully created a new default channel.
Joining peers to the default channel.
Peer joined default channel
Peer joined default channel
Peer joined default channel
Peer joined default channel
Connecting and Registering Block Events
Chaincode is not installed, attempting installation...
Base container image present.
Successfully installed chaincode on the default channel.
Fatal error instantiating chaincode on some(all) peers!
Error: Proposal rejected by some (all) of the peers: Error: error starting container: error starting container: API error (404): network build-blockchain-insurance-app_default not found
    at /app/www/blockchain/utils.js:243:15
    at Generator.next (<anonymous>)
    at step (/app/bin/blockchain/utils.js:103:191)
    at /app/bin/blockchain/utils.js:103:361
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! blockchain-for-insurance@2.1.1 serve: `cross-env NODE_ENV=production&&node ./bin/server`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the blockchain-for-insurance@2.1.1 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-18T11_25_36_530Z-debug.log

Above is what I get on running `docker logs web` after running the ubuntu build.
I have currently docker version - 18.09.6 and docker-compose version 1.24.0 on  my system.
The peer-base.yaml contains the below snippet so the solution to the issue #69 is not working.
`CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=build-blockchain-insurance-app_default`

According to the log, peers are joining the default channel and the chaincode too got installed on the default channel, thus the default channel is formed and running. But at the time of peers accepting the proposal, it returns a 404 and states network not found.

**Comment by varunagarwal315** [comment]
Replace it to
`CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=buildblockchaininsuranceapp_default`
afaik docker doesnt allow - and spaces in this name.

**Comment by vaibhavr2709** [comment]
Tried still the same error. I'm not able to get to the root of the error.

**Comment by vaibhavr2709** [comment]
> npm ERR! blockchain-for-insurance@2.1.1 serve: cross-env NODE_ENV=production&&node ./bin/server

What does this exactly mean?

**Comment by vaibhavr2709** [comment]
Finally the error is resolved and below is the fix to it.

Two files need to be modified. Make sure your files look like the ones below.

1)    build-blockchain-insuarance-app/web/Dockerfile

>  FROM docker.io/library/node:8.9.0
    ENV NODE_ENV production
    ENV PORT 3000
    ENV DOCKER_SOCKET_PATH /host/var/run/docker.sock
    ENV DOCKER_CCENV_IMAGE hyperledger/fabric-ccenv:latest
    RUN mkdir /app
    COPY . /app
    WORKDIR /app
    RUN npm i && npm i --only=dev
    && npm run build
    && npm prune
    EXPOSE 3000
    CMD ["npm", "run", "serve"]

2)    build-blockchain-insuarance-app/peer-base.yaml

>  version: '2'
    services:
    peer-base:
    environment:
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=buildblockchaininsuranceapp_default
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_ENDORSER_ENABLED=true
    - CORE_PEER_GOSSIP_USELEADERELECTION=true
    - CORE_PEER_GOSSIP_ORGLEADER=false
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_MSPCONFIGPATH=/peer/crypto/msp
    - CORE_PEER_TLS_CERT_FILE=/peer/crypto/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/peer/crypto/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/peer/crypto/tls/ca.crt
    working_dir: /peer
    command: peer node start
    volumes:
    - /var/run/:/host/var/run/

Note that in second file the value of CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE has been altered, to be specific the dashes have been removed else you'll get a 404 error.

That's all. This would work probably. I recommend you to start afresh and thus remove all the containers formed due to previous runnings of the build. In a nutshell follow the below steps and you'll be good to go.

    Make sure you've made the necessary changes to the files mentioned above.

    Run the commands below once you get into the dir where build_ubuntu.sh resides.

`docker stop $(docker ps -aq) && docker rm $(docker ps -aq)`
`docker login`
`./build_ubuntu.sh`
`docker logs web`

You'll notice the chaincode has been successfully instantiated.
