### ISSUE TITLE
web node run into error

### ISSUE THREAD

**Issue by aceyin** [IBM/build-blockchain-insurance-app#8]
Error getting theft claims "list" argument must be an Array of Buffers
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: Error executing chaincode: premature execution - chaincode (bcins:v2) is being launched
    at new createStatusError (/app/node_modules/grpc/src/client.js:65:15)
    at /app/node_modules/grpc/src/client.js:568:15
Error getting theft claims "list" argument must be an Array of Buffers

FABRIC VERSION: x86_64-1.0.4
RUN ON: Mac

**Comment by ishangulhane** [comment]
@aceyin I not able to recreate the issue. Follow the troubleshooting steps to clean the network.

**Comment by mgcox** [comment]
Was there ever a fix to this? I am having the same problem

**Comment by ljbennett62** [comment]
@mgcox @aceyin - your Fabric version should be x86-1.1.1.  I have 1) updated the code and readme 3) pulled down to my local version and was successfully able to build and deploy the application. So I would suggest that you start fresh: 1) pull the latest code 2) clear out all your images using a docker stop and docker rmi commands 3) make sure you have the right version of node by installing nvm and pointing to the node version 8.11.3, docker 1.8 and npm 5.6.0. 3) Then dependent on your platform- run the right build command and everything should work.
