### ISSUE TITLE
Further Documentation typos and missing information

### ISSUE THREAD

**Issue by lesleyannjordan** [IBM/build-blockchain-insurance-app#83]
Description: I am following the tutorial below,

https://github.com/IBM/build-blockchain-insurance-app/blob/master/README.md#step-7-Deploy-Insurance-Smart-Contract-on-the-network

1)
    I checked again the tutorial and it makes sense, but in Step 4. Build a network - Create Peers, it seems to has the same typos as ticket #82 

    In the following text maybe "Shop MSP" must be replaced by "Repair Shop MSP". The same happen for the "police peer".
    But "maybe I am wrong"?

    Create a repair shop peer (same process as shown in gif above)
    -On the Nodes page, click Add peer.
    -Click IBM Cloud under Create a new peer and Next.
    -Give your peer a Display name of Repair Shop Peer.
    -On the next screen, select Repair Shop CA as your Certificate Authority. Then, give the Enroll ID and Enroll secret for the peer identity that you created for your peer, repairShopPeer, and repairShopPeerpw. Then, select the Administrator Certificate (from MSP), Shop MSP, from the drop-down list and click Next.
    -Give the TLS Enroll ID, admin, and TLS Enroll secret, adminpw, the same values are the Enroll ID and Enroll secret that you gave when creating the CA. Leave the TLS CSR hostname blank.
    -The last side panel will ask you to Associate an identity and make it the admin of your peer. Select your peer admin identity Repair Shop Admin.
    -Review the summary and click Submit.

Please review and update as appropriate.  Please check the rest of the tutorial for similar typos.

2)
During execution of Step 7. Deploy Insurance Smart Contract on the network.
The documentation indicates 4 sub-steps, but the video and execution shows 5.
The missing documented step is around what peer should be chosen?
Which Peer I should select from "Select Peer". Anyways, I chose "Insurance Peer". Is that correct?.

**Comment by horeaporutiu** [comment]
Thank you, closed with https://github.com/IBM/build-blockchain-insurance-app/commit/902d84ad583296201c9652a966745de66688abd4

**Comment by cgironda** [comment]
Behind a proxi correctly configured  under the following configuration:
`node -v`: `v8.16.0` or `v10.16.0`
`npm -v`: `v6.9.0`

I executed the **Step 9. Enroll App Admin Identities**, of the tutorial:

https://github.com/IBM/build-blockchain-insurance-app/blob/master/README.md#step-7-Deploy-Insurance-Smart-Contract-on-the-network

obtaining the error below:

```$node enrollAdmin.js 
Wallet path: /Users/$USER/Documents/IBM_Blockchain/build-blockchain-insurance-app/web/www/blockchain/wallet 2019-07-26T07:21:30.855Z - error: [FabricCAClientService.js]: Failed to enroll insuranceApp-admin, error:%o message=Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 169.60.31.202:7054], stack=Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 169.60.31.202:7054] at ClientRequest.request.on (/Users/$USER/Documents/IBM_Blockchain/build-blockchain-insurance-app/web/node_modules/fabric-ca-client/lib/FabricCAClient.js:487:12) at emitOne (events.js:116:13) at ClientRequest.emit (events.js:211:7) at TLSSocket.socketErrorListener (_http_client.js:387:9) at emitOne (events.js:116:13) at TLSSocket.emit (events.js:211:7) at emitErrorNT (internal/streams/destroy.js:64:8) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9) Failed to enroll admin user ' + insuranceApp-admin + : Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 169.60.31.202:7054] 
```

This error seems that appear when docker "containers are not available", but please can you **confirm** that issue?.

Thank you
