### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by cgironda** [IBM/build-blockchain-insurance-app#85]
Hi,

Please check the **STEP Step 8. Connect application to the network**, where it seems has some typos similar to the issues found in **Documentation duplicate typo - possibly? Please confirm #82**, and **Further Documentation typos and missing information #83**.

For example,

**Create police application admin (same process as shown above in the gif)**
- Go to the Nodes tab on the left bar, and under Certificate Authorities, choose your Shop CA.

maybe is,

**Create police application admin (same process as shown above in the gif)**
- Go to the Nodes tab on the left bar, and under Certificate Authorities, choose your Police CA.

Same for **repair shop**.

Thank you.

**Comment by horeaporutiu** [comment]
hi @cgironda this issue has been resolved with the following commit: https://github.com/IBM/build-blockchain-insurance-app/commit/e76859f7343f0803cf1a9d6420ab84c16395cc40

Sorry for any inconvenience caused.
