### ISSUE TITLE
How to check this kind of view in Local

### ISSUE THREAD

**Issue by SailendraDs** [IBM/build-blockchain-insurance-app#98]
Hi,

    I've checked the video which shows IBM platform Transactions & Blocks. Refer the Pics below:
![1](https://user-images.githubusercontent.com/42380691/76185582-9a30e980-61f5-11ea-8e10-3e964e064c02.JPG)
![Capture](https://user-images.githubusercontent.com/42380691/76185586-a026ca80-61f5-11ea-90c3-86940782e42f.JPG)

Please let me know

**Comment by SailendraDs** [comment]
or How i can make this?

**Comment by horeaporutiu** [comment]
@SailendraDs 

You can see a similar block explorer in the local version as shown in this screenshot _ https://github.com/IBM/build-blockchain-insurance-app/blob/master/images/Picture6.png

**Comment by horeaporutiu** [comment]
You can see the code to do this in the [utils file](https://github.com/IBM/build-blockchain-insurance-app/blob/master/web/www/blockchain/utils.js#L85) - we are registering and listening for block events. IBM Blockchain Platform does this for us automatically. That is one advantage of using the IBM Blockchain Platform over Hyperledger Fabric.

**Comment by SailendraDs** [comment]
I mean is there any ledger like thing to show the transactions in it by other usernames as well?
